// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfeature.h"

extern XFeature_Config XFeature_ConfigTable[];

XFeature_Config *XFeature_LookupConfig(u16 DeviceId) {
	XFeature_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFEATURE_NUM_INSTANCES; Index++) {
		if (XFeature_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFeature_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFeature_Initialize(XFeature *InstancePtr, u16 DeviceId) {
	XFeature_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFeature_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFeature_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

