// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfeature.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFeature_CfgInitialize(XFeature *InstancePtr, XFeature_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFeature_Start(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFeature_IsDone(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFeature_IsIdle(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFeature_IsReady(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFeature_EnableAutoRestart(XFeature *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XFeature_DisableAutoRestart(XFeature *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XFeature_Set_frame_in(XFeature *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_FRAME_IN_DATA, Data);
}

u32 XFeature_Get_frame_in(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_FRAME_IN_DATA);
    return Data;
}

void XFeature_Set_bounding(XFeature *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_BOUNDING_DATA, Data);
}

u32 XFeature_Get_bounding(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_BOUNDING_DATA);
    return Data;
}

void XFeature_Set_featureh(XFeature *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_FEATUREH_DATA, Data);
}

u32 XFeature_Get_featureh(XFeature *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFeature_ReadReg(InstancePtr->Axilites_BaseAddress, XFEATURE_AXILITES_ADDR_FEATUREH_DATA);
    return Data;
}

void XFeature_InterruptGlobalEnable(XFeature *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_GIE, 1);
}

void XFeature_InterruptGlobalDisable(XFeature *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_GIE, 0);
}

void XFeature_InterruptEnable(XFeature *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_IER);
    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XFeature_InterruptDisable(XFeature *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_IER);
    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XFeature_InterruptClear(XFeature *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFeature_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XFeature_InterruptGetEnabled(XFeature *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_IER);
}

u32 XFeature_InterruptGetStatus(XFeature *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFeature_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XFEATURE_CRTL_BUS_ADDR_ISR);
}

