webtalk_init -webtalk_dir /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan 13 19:36:15 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4jn4ist1nahic5b2oftqvjobad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1515848146000" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1515848146000"
webtalk_add_data -client sdk -key uid -value "1515848203000" -context "sdk\\\\bsp/1515848203000"
webtalk_add_data -client sdk -key hwid -value "1515848146000" -context "sdk\\\\bsp/1515848203000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1515848203000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1515848203000"
webtalk_add_data -client sdk -key uid -value "1515848214000" -context "sdk\\\\application/1515848214000"
webtalk_add_data -client sdk -key hwid -value "1515848146000" -context "sdk\\\\application/1515848214000"
webtalk_add_data -client sdk -key bspid -value "1515848203000" -context "sdk\\\\application/1515848214000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1515848214000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1515848214000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1515848214000"
webtalk_transmit -clientid 487413201 -regid "" -xml /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
