# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.cache/wt [current_project]
set_property parent.project_path /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/chathura/Desktop/maxi_final_180113/backsub_gmm_new_180110
  /home/chathura/Desktop/maxi_final_180113/maxi_feature
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_bgsub_0_0/constraints/bgsub_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_feature_0_0/constraints/feature_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_feature_0_1/constraints/feature_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_feature_0_2/constraints/feature_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s07_mmu_0/design_1_s07_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s06_mmu_0/design_1_s06_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s05_mmu_0/design_1_s05_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s04_mmu_0/design_1_s04_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s03_mmu_0/design_1_s03_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s02_mmu_0/design_1_s02_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_7/design_1_auto_cc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_7/design_1_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_8/design_1_auto_cc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_8/design_1_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_9/design_1_auto_cc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_9/design_1_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_10/design_1_auto_cc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_10/design_1_auto_cc_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_11/design_1_auto_cc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_11/design_1_auto_cc_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /home/chathura/Desktop/maxi_final_180113/maxi_vivado_180113/maxi_vivado_180113.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
