# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_bgsub_0_0/design_1_bgsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bgsub_0_0 || ORIG_REF_NAME==design_1_bgsub_0_0}]

# IP: bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_1_processing_system7_0_axi_periph_0}]

# IP: bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_142M_0}]

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: bd/design_1/ip/design_1_axi_mem_intercon_0/design_1_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0}]

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0}]

# IP: bd/design_1/ip/design_1_feature_0_0/design_1_feature_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_feature_0_0 || ORIG_REF_NAME==design_1_feature_0_0}]

# IP: bd/design_1/ip/design_1_feature_0_1/design_1_feature_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_feature_0_1 || ORIG_REF_NAME==design_1_feature_0_1}]

# IP: bd/design_1/ip/design_1_feature_0_2/design_1_feature_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_feature_0_2 || ORIG_REF_NAME==design_1_feature_0_2}]

# IP: bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_250M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_250M_0}]

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0}]

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0}]

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1}]

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2}]

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}]

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3}]

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}]

# IP: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4}]

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2}]

# IP: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5}]

# IP: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3}]

# IP: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6}]

# IP: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4}]

# IP: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7}]

# IP: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_5 || ORIG_REF_NAME==design_1_auto_cc_5}]

# IP: bd/design_1/ip/design_1_s07_mmu_0/design_1_s07_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s07_mmu_0 || ORIG_REF_NAME==design_1_s07_mmu_0}]

# IP: bd/design_1/ip/design_1_s06_mmu_0/design_1_s06_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s06_mmu_0 || ORIG_REF_NAME==design_1_s06_mmu_0}]

# IP: bd/design_1/ip/design_1_s05_mmu_0/design_1_s05_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s05_mmu_0 || ORIG_REF_NAME==design_1_s05_mmu_0}]

# IP: bd/design_1/ip/design_1_s04_mmu_0/design_1_s04_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s04_mmu_0 || ORIG_REF_NAME==design_1_s04_mmu_0}]

# IP: bd/design_1/ip/design_1_s03_mmu_0/design_1_s03_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s03_mmu_0 || ORIG_REF_NAME==design_1_s03_mmu_0}]

# IP: bd/design_1/ip/design_1_s02_mmu_0/design_1_s02_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s02_mmu_0 || ORIG_REF_NAME==design_1_s02_mmu_0}]

# IP: bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_mmu_0 || ORIG_REF_NAME==design_1_s01_mmu_0}]

# IP: bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_mmu_0 || ORIG_REF_NAME==design_1_s00_mmu_0}]

# IP: bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_6 || ORIG_REF_NAME==design_1_auto_cc_6}]

# IP: bd/design_1/ip/design_1_auto_cc_7/design_1_auto_cc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_7 || ORIG_REF_NAME==design_1_auto_cc_7}]

# IP: bd/design_1/ip/design_1_auto_cc_8/design_1_auto_cc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_8 || ORIG_REF_NAME==design_1_auto_cc_8}]

# IP: bd/design_1/ip/design_1_auto_cc_9/design_1_auto_cc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_9 || ORIG_REF_NAME==design_1_auto_cc_9}]

# IP: bd/design_1/ip/design_1_auto_cc_10/design_1_auto_cc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_10 || ORIG_REF_NAME==design_1_auto_cc_10}]

# IP: bd/design_1/ip/design_1_auto_cc_11/design_1_auto_cc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_11 || ORIG_REF_NAME==design_1_auto_cc_11}]

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1}]

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_bgsub_0_0/constraints/bgsub_ooc.xdc

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_142M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_142M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_142M_0/design_1_rst_processing_system7_0_142M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_feature_0_0/constraints/feature_ooc.xdc

# XDC: bd/design_1/ip/design_1_feature_0_1/constraints/feature_ooc.xdc

# XDC: bd/design_1/ip/design_1_feature_0_2/constraints/feature_ooc.xdc

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_250M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_250M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_250M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_250M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_250M_0/design_1_rst_processing_system7_0_250M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_5 || ORIG_REF_NAME==design_1_auto_cc_5}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_s07_mmu_0/design_1_s07_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s06_mmu_0/design_1_s06_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s05_mmu_0/design_1_s05_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s04_mmu_0/design_1_s04_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s03_mmu_0/design_1_s03_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s02_mmu_0/design_1_s02_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_6 || ORIG_REF_NAME==design_1_auto_cc_6}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_7/design_1_auto_cc_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_7/design_1_auto_cc_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_7 || ORIG_REF_NAME==design_1_auto_cc_7}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_8/design_1_auto_cc_8_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_8/design_1_auto_cc_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_8 || ORIG_REF_NAME==design_1_auto_cc_8}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_9/design_1_auto_cc_9_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_9/design_1_auto_cc_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_9 || ORIG_REF_NAME==design_1_auto_cc_9}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_10/design_1_auto_cc_10_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_10/design_1_auto_cc_10_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_10 || ORIG_REF_NAME==design_1_auto_cc_10}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_11/design_1_auto_cc_11_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_11/design_1_auto_cc_11_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_11 || ORIG_REF_NAME==design_1_auto_cc_11}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
