// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbgsub.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBgsub_CfgInitialize(XBgsub *InstancePtr, XBgsub_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBgsub_Start(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBgsub_IsDone(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBgsub_IsIdle(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBgsub_IsReady(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBgsub_EnableAutoRestart(XBgsub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XBgsub_DisableAutoRestart(XBgsub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XBgsub_Set_init(XBgsub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_INIT_DATA, Data);
}

u32 XBgsub_Get_init(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_INIT_DATA);
    return Data;
}

void XBgsub_Set_frame_in(XBgsub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_FRAME_IN_DATA, Data);
}

u32 XBgsub_Get_frame_in(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_FRAME_IN_DATA);
    return Data;
}

void XBgsub_Set_frame_out(XBgsub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_FRAME_OUT_DATA, Data);
}

u32 XBgsub_Get_frame_out(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_FRAME_OUT_DATA);
    return Data;
}

void XBgsub_Set_bgmodel(XBgsub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_BGMODEL_DATA, Data);
}

u32 XBgsub_Get_bgmodel(XBgsub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBgsub_ReadReg(InstancePtr->Axilites_BaseAddress, XBGSUB_AXILITES_ADDR_BGMODEL_DATA);
    return Data;
}

void XBgsub_InterruptGlobalEnable(XBgsub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_GIE, 1);
}

void XBgsub_InterruptGlobalDisable(XBgsub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_GIE, 0);
}

void XBgsub_InterruptEnable(XBgsub *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_IER);
    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XBgsub_InterruptDisable(XBgsub *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_IER);
    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XBgsub_InterruptClear(XBgsub *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBgsub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XBgsub_InterruptGetEnabled(XBgsub *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_IER);
}

u32 XBgsub_InterruptGetStatus(XBgsub *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBgsub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBGSUB_CRTL_BUS_ADDR_ISR);
}

