// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="feature,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=1,HLS_SYN_TPT=348394,HLS_SYN_MEM=3,HLS_SYN_DSP=1,HLS_SYN_FF=1966,HLS_SYN_LUT=3148}" *)

module feature (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        s_axi_CRTL_BUS_AWVALID,
        s_axi_CRTL_BUS_AWREADY,
        s_axi_CRTL_BUS_AWADDR,
        s_axi_CRTL_BUS_WVALID,
        s_axi_CRTL_BUS_WREADY,
        s_axi_CRTL_BUS_WDATA,
        s_axi_CRTL_BUS_WSTRB,
        s_axi_CRTL_BUS_ARVALID,
        s_axi_CRTL_BUS_ARREADY,
        s_axi_CRTL_BUS_ARADDR,
        s_axi_CRTL_BUS_RVALID,
        s_axi_CRTL_BUS_RREADY,
        s_axi_CRTL_BUS_RDATA,
        s_axi_CRTL_BUS_RRESP,
        s_axi_CRTL_BUS_BVALID,
        s_axi_CRTL_BUS_BREADY,
        s_axi_CRTL_BUS_BRESP,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        m_axi_gmem_offset_AWVALID,
        m_axi_gmem_offset_AWREADY,
        m_axi_gmem_offset_AWADDR,
        m_axi_gmem_offset_AWID,
        m_axi_gmem_offset_AWLEN,
        m_axi_gmem_offset_AWSIZE,
        m_axi_gmem_offset_AWBURST,
        m_axi_gmem_offset_AWLOCK,
        m_axi_gmem_offset_AWCACHE,
        m_axi_gmem_offset_AWPROT,
        m_axi_gmem_offset_AWQOS,
        m_axi_gmem_offset_AWREGION,
        m_axi_gmem_offset_AWUSER,
        m_axi_gmem_offset_WVALID,
        m_axi_gmem_offset_WREADY,
        m_axi_gmem_offset_WDATA,
        m_axi_gmem_offset_WSTRB,
        m_axi_gmem_offset_WLAST,
        m_axi_gmem_offset_WID,
        m_axi_gmem_offset_WUSER,
        m_axi_gmem_offset_ARVALID,
        m_axi_gmem_offset_ARREADY,
        m_axi_gmem_offset_ARADDR,
        m_axi_gmem_offset_ARID,
        m_axi_gmem_offset_ARLEN,
        m_axi_gmem_offset_ARSIZE,
        m_axi_gmem_offset_ARBURST,
        m_axi_gmem_offset_ARLOCK,
        m_axi_gmem_offset_ARCACHE,
        m_axi_gmem_offset_ARPROT,
        m_axi_gmem_offset_ARQOS,
        m_axi_gmem_offset_ARREGION,
        m_axi_gmem_offset_ARUSER,
        m_axi_gmem_offset_RVALID,
        m_axi_gmem_offset_RREADY,
        m_axi_gmem_offset_RDATA,
        m_axi_gmem_offset_RLAST,
        m_axi_gmem_offset_RID,
        m_axi_gmem_offset_RUSER,
        m_axi_gmem_offset_RRESP,
        m_axi_gmem_offset_BVALID,
        m_axi_gmem_offset_BREADY,
        m_axi_gmem_offset_BRESP,
        m_axi_gmem_offset_BID,
        m_axi_gmem_offset_BUSER
);

parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    ap_const_logic_1 = 1'b1;
parameter    C_S_AXI_CRTL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CRTL_BUS_ADDR_WIDTH = 5;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_OFFSET_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_OFFSET_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OFFSET_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OFFSET_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_OFFSET_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_OFFSET_CACHE_VALUE = 3;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_true = 1'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv16_1 = 16'b1;
parameter    C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_CRTL_BUS_WSTRB_WIDTH = (C_S_AXI_CRTL_BUS_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_GMEM_WSTRB_WIDTH = (C_M_AXI_GMEM_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_WSTRB_WIDTH = (C_M_AXI_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_GMEM_OFFSET_WSTRB_WIDTH = (C_M_AXI_GMEM_OFFSET_DATA_WIDTH / ap_const_int64_8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
input   s_axi_CRTL_BUS_AWVALID;
output   s_axi_CRTL_BUS_AWREADY;
input  [C_S_AXI_CRTL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CRTL_BUS_AWADDR;
input   s_axi_CRTL_BUS_WVALID;
output   s_axi_CRTL_BUS_WREADY;
input  [C_S_AXI_CRTL_BUS_DATA_WIDTH - 1 : 0] s_axi_CRTL_BUS_WDATA;
input  [C_S_AXI_CRTL_BUS_WSTRB_WIDTH - 1 : 0] s_axi_CRTL_BUS_WSTRB;
input   s_axi_CRTL_BUS_ARVALID;
output   s_axi_CRTL_BUS_ARREADY;
input  [C_S_AXI_CRTL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CRTL_BUS_ARADDR;
output   s_axi_CRTL_BUS_RVALID;
input   s_axi_CRTL_BUS_RREADY;
output  [C_S_AXI_CRTL_BUS_DATA_WIDTH - 1 : 0] s_axi_CRTL_BUS_RDATA;
output  [1:0] s_axi_CRTL_BUS_RRESP;
output   s_axi_CRTL_BUS_BVALID;
input   s_axi_CRTL_BUS_BREADY;
output  [1:0] s_axi_CRTL_BUS_BRESP;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1 : 0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1 : 0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1 : 0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1 : 0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1 : 0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1 : 0] m_axi_gmem_BUSER;
output   m_axi_gmem_offset_AWVALID;
input   m_axi_gmem_offset_AWREADY;
output  [C_M_AXI_GMEM_OFFSET_ADDR_WIDTH - 1 : 0] m_axi_gmem_offset_AWADDR;
output  [C_M_AXI_GMEM_OFFSET_ID_WIDTH - 1 : 0] m_axi_gmem_offset_AWID;
output  [7:0] m_axi_gmem_offset_AWLEN;
output  [2:0] m_axi_gmem_offset_AWSIZE;
output  [1:0] m_axi_gmem_offset_AWBURST;
output  [1:0] m_axi_gmem_offset_AWLOCK;
output  [3:0] m_axi_gmem_offset_AWCACHE;
output  [2:0] m_axi_gmem_offset_AWPROT;
output  [3:0] m_axi_gmem_offset_AWQOS;
output  [3:0] m_axi_gmem_offset_AWREGION;
output  [C_M_AXI_GMEM_OFFSET_AWUSER_WIDTH - 1 : 0] m_axi_gmem_offset_AWUSER;
output   m_axi_gmem_offset_WVALID;
input   m_axi_gmem_offset_WREADY;
output  [C_M_AXI_GMEM_OFFSET_DATA_WIDTH - 1 : 0] m_axi_gmem_offset_WDATA;
output  [C_M_AXI_GMEM_OFFSET_WSTRB_WIDTH - 1 : 0] m_axi_gmem_offset_WSTRB;
output   m_axi_gmem_offset_WLAST;
output  [C_M_AXI_GMEM_OFFSET_ID_WIDTH - 1 : 0] m_axi_gmem_offset_WID;
output  [C_M_AXI_GMEM_OFFSET_WUSER_WIDTH - 1 : 0] m_axi_gmem_offset_WUSER;
output   m_axi_gmem_offset_ARVALID;
input   m_axi_gmem_offset_ARREADY;
output  [C_M_AXI_GMEM_OFFSET_ADDR_WIDTH - 1 : 0] m_axi_gmem_offset_ARADDR;
output  [C_M_AXI_GMEM_OFFSET_ID_WIDTH - 1 : 0] m_axi_gmem_offset_ARID;
output  [7:0] m_axi_gmem_offset_ARLEN;
output  [2:0] m_axi_gmem_offset_ARSIZE;
output  [1:0] m_axi_gmem_offset_ARBURST;
output  [1:0] m_axi_gmem_offset_ARLOCK;
output  [3:0] m_axi_gmem_offset_ARCACHE;
output  [2:0] m_axi_gmem_offset_ARPROT;
output  [3:0] m_axi_gmem_offset_ARQOS;
output  [3:0] m_axi_gmem_offset_ARREGION;
output  [C_M_AXI_GMEM_OFFSET_ARUSER_WIDTH - 1 : 0] m_axi_gmem_offset_ARUSER;
input   m_axi_gmem_offset_RVALID;
output   m_axi_gmem_offset_RREADY;
input  [C_M_AXI_GMEM_OFFSET_DATA_WIDTH - 1 : 0] m_axi_gmem_offset_RDATA;
input   m_axi_gmem_offset_RLAST;
input  [C_M_AXI_GMEM_OFFSET_ID_WIDTH - 1 : 0] m_axi_gmem_offset_RID;
input  [C_M_AXI_GMEM_OFFSET_RUSER_WIDTH - 1 : 0] m_axi_gmem_offset_RUSER;
input  [1:0] m_axi_gmem_offset_RRESP;
input   m_axi_gmem_offset_BVALID;
output   m_axi_gmem_offset_BREADY;
input  [1:0] m_axi_gmem_offset_BRESP;
input  [C_M_AXI_GMEM_OFFSET_ID_WIDTH - 1 : 0] m_axi_gmem_offset_BID;
input  [C_M_AXI_GMEM_OFFSET_BUSER_WIDTH - 1 : 0] m_axi_gmem_offset_BUSER;

reg    ap_rst_n_inv;
wire    feature_AXILiteS_s_axi_U_ap_dummy_ce;
wire   [31:0] frame_in;
wire   [31:0] bounding;
wire   [31:0] featureh;
wire    feature_CRTL_BUS_s_axi_U_ap_dummy_ce;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire    gmem_AWVALID;
wire    gmem_AWREADY;
wire   [31:0] gmem_AWADDR;
wire   [0:0] gmem_AWID;
wire   [31:0] gmem_AWLEN;
wire   [2:0] gmem_AWSIZE;
wire   [1:0] gmem_AWBURST;
wire   [1:0] gmem_AWLOCK;
wire   [3:0] gmem_AWCACHE;
wire   [2:0] gmem_AWPROT;
wire   [3:0] gmem_AWQOS;
wire   [3:0] gmem_AWREGION;
wire   [0:0] gmem_AWUSER;
wire    gmem_WVALID;
wire    gmem_WREADY;
wire   [7:0] gmem_WDATA;
wire   [0:0] gmem_WSTRB;
wire    gmem_WLAST;
wire   [0:0] gmem_WID;
wire   [0:0] gmem_WUSER;
wire    gmem_ARVALID;
wire    gmem_ARREADY;
wire   [31:0] gmem_ARADDR;
wire   [0:0] gmem_ARID;
wire   [31:0] gmem_ARLEN;
wire   [2:0] gmem_ARSIZE;
wire   [1:0] gmem_ARBURST;
wire   [1:0] gmem_ARLOCK;
wire   [3:0] gmem_ARCACHE;
wire   [2:0] gmem_ARPROT;
wire   [3:0] gmem_ARQOS;
wire   [3:0] gmem_ARREGION;
wire   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
wire    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    feature_gmem_m_axi_U_ap_dummy_ce;
wire    gmem_offset_AWVALID;
wire    gmem_offset_AWREADY;
wire   [31:0] gmem_offset_AWADDR;
wire   [0:0] gmem_offset_AWID;
wire   [31:0] gmem_offset_AWLEN;
wire   [2:0] gmem_offset_AWSIZE;
wire   [1:0] gmem_offset_AWBURST;
wire   [1:0] gmem_offset_AWLOCK;
wire   [3:0] gmem_offset_AWCACHE;
wire   [2:0] gmem_offset_AWPROT;
wire   [3:0] gmem_offset_AWQOS;
wire   [3:0] gmem_offset_AWREGION;
wire   [0:0] gmem_offset_AWUSER;
wire    gmem_offset_WVALID;
wire    gmem_offset_WREADY;
wire   [15:0] gmem_offset_WDATA;
wire   [1:0] gmem_offset_WSTRB;
wire    gmem_offset_WLAST;
wire   [0:0] gmem_offset_WID;
wire   [0:0] gmem_offset_WUSER;
wire    gmem_offset_ARVALID;
wire    gmem_offset_ARREADY;
wire   [31:0] gmem_offset_ARADDR;
wire   [0:0] gmem_offset_ARID;
wire   [31:0] gmem_offset_ARLEN;
wire   [2:0] gmem_offset_ARSIZE;
wire   [1:0] gmem_offset_ARBURST;
wire   [1:0] gmem_offset_ARLOCK;
wire   [3:0] gmem_offset_ARCACHE;
wire   [2:0] gmem_offset_ARPROT;
wire   [3:0] gmem_offset_ARQOS;
wire   [3:0] gmem_offset_ARREGION;
wire   [0:0] gmem_offset_ARUSER;
wire    gmem_offset_RVALID;
wire    gmem_offset_RREADY;
wire   [15:0] gmem_offset_RDATA;
wire    gmem_offset_RLAST;
wire   [0:0] gmem_offset_RID;
wire   [0:0] gmem_offset_RUSER;
wire   [1:0] gmem_offset_RRESP;
wire    gmem_offset_BVALID;
wire    gmem_offset_BREADY;
wire   [1:0] gmem_offset_BRESP;
wire   [0:0] gmem_offset_BID;
wire   [0:0] gmem_offset_BUSER;
wire    feature_gmem_offset_m_axi_U_ap_dummy_ce;
wire   [8:0] featureHist_i_address0;
wire    featureHist_i_ce0;
wire    featureHist_i_we0;
wire   [15:0] featureHist_i_d0;
wire   [15:0] featureHist_i_q0;
wire   [8:0] featureHist_i_address1;
wire    featureHist_i_ce1;
wire    featureHist_i_we1;
wire   [15:0] featureHist_i_d1;
wire   [15:0] featureHist_i_q1;
wire   [8:0] featureHist_t_address0;
wire    featureHist_t_ce0;
wire    featureHist_t_we0;
wire   [15:0] featureHist_t_d0;
wire   [15:0] featureHist_t_q0;
wire   [8:0] featureHist_t_address1;
wire    featureHist_t_ce1;
wire    featureHist_t_we1;
wire   [15:0] featureHist_t_d1;
wire   [15:0] featureHist_t_q1;
wire    featureHist_U_ap_dummy_ce;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done;
reg    feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_ap_idle;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWVALID;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWREADY;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWADDR;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWID;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWLEN;
wire   [2:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWSIZE;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWBURST;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWLOCK;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWCACHE;
wire   [2:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWPROT;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWQOS;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWREGION;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWUSER;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WVALID;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WREADY;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WDATA;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WSTRB;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WLAST;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WID;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WUSER;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARVALID;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREADY;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARADDR;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARID;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLEN;
wire   [2:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARSIZE;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARBURST;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLOCK;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARCACHE;
wire   [2:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARPROT;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARQOS;
wire   [3:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREGION;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARUSER;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RVALID;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RREADY;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RDATA;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RLAST;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RID;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RUSER;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RRESP;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BVALID;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BREADY;
wire   [1:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BRESP;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BID;
wire   [0:0] feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BUSER;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_bounding1;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_featureh;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_din;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_full_n;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_write;
wire   [31:0] feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_din;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_full_n;
wire    feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_write;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_0;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_1;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_2;
wire   [15:0] feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_3;
reg    ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_0_loc_channel;
wire    boundingBoxes_0_loc_channel_full_n;
reg    ap_reg_ready_boundingBoxes_0_loc_channel_full_n = 1'b0;
reg    ap_sig_ready_boundingBoxes_0_loc_channel_full_n;
reg    ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_2_loc_channel;
wire    boundingBoxes_2_loc_channel_full_n;
reg    ap_reg_ready_boundingBoxes_2_loc_channel_full_n = 1'b0;
reg    ap_sig_ready_boundingBoxes_2_loc_channel_full_n;
reg    ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_3_loc_channel;
wire    boundingBoxes_3_loc_channel_full_n;
reg    ap_reg_ready_boundingBoxes_3_loc_channel_full_n = 1'b0;
reg    ap_sig_ready_boundingBoxes_3_loc_channel_full_n;
reg    ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_1_loc_channel;
wire    boundingBoxes_1_loc_channel_full_n;
reg    ap_reg_ready_boundingBoxes_1_loc_channel_full_n = 1'b0;
reg    ap_sig_ready_boundingBoxes_1_loc_channel_full_n;
wire    feature_Loop_memset_featureHist_proc1_U0_ap_start;
wire    feature_Loop_memset_featureHist_proc1_U0_ap_done;
wire    feature_Loop_memset_featureHist_proc1_U0_ap_continue;
wire    feature_Loop_memset_featureHist_proc1_U0_ap_idle;
wire    feature_Loop_memset_featureHist_proc1_U0_ap_ready;
wire   [8:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_address0;
wire    feature_Loop_memset_featureHist_proc1_U0_featureHist_ce0;
wire    feature_Loop_memset_featureHist_proc1_U0_featureHist_we0;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_d0;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_q0;
wire   [8:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_address1;
wire    feature_Loop_memset_featureHist_proc1_U0_featureHist_ce1;
wire    feature_Loop_memset_featureHist_proc1_U0_featureHist_we1;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_d1;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_featureHist_q1;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWVALID;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWREADY;
wire   [31:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWADDR;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWID;
wire   [31:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWLEN;
wire   [2:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWSIZE;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWBURST;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWLOCK;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWCACHE;
wire   [2:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWPROT;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWQOS;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWREGION;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWUSER;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WVALID;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WREADY;
wire   [7:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WDATA;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WSTRB;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WLAST;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WID;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WUSER;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARVALID;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREADY;
wire   [31:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARADDR;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARID;
wire   [31:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLEN;
wire   [2:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARSIZE;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARBURST;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLOCK;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARCACHE;
wire   [2:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARPROT;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARQOS;
wire   [3:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREGION;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARUSER;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RVALID;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RREADY;
wire   [7:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RDATA;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RLAST;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RID;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RUSER;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RRESP;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BVALID;
wire    feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BREADY;
wire   [1:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BRESP;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BID;
wire   [0:0] feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BUSER;
wire   [31:0] feature_Loop_memset_featureHist_proc1_U0_frame_in1_dout;
wire    feature_Loop_memset_featureHist_proc1_U0_frame_in1_empty_n;
wire    feature_Loop_memset_featureHist_proc1_U0_frame_in1_read;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_p_read;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_p_read1;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_p_read2;
wire   [15:0] feature_Loop_memset_featureHist_proc1_U0_p_read3;
wire    ap_chn_write_feature_Loop_memset_featureHist_proc1_U0_featureHist;
wire    feature_Loop_memset_featureHist_proc1_U0_featureHist_pipo_status;
wire    feature_Loop_memcpy_featureh_featureHi_U0_ap_start;
wire    feature_Loop_memcpy_featureh_featureHi_U0_ap_done;
wire    feature_Loop_memcpy_featureh_featureHi_U0_ap_continue;
wire    feature_Loop_memcpy_featureh_featureHi_U0_ap_idle;
wire    feature_Loop_memcpy_featureh_featureHi_U0_ap_ready;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWVALID;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREADY;
wire   [31:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWADDR;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWID;
wire   [31:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLEN;
wire   [2:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWSIZE;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWBURST;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLOCK;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWCACHE;
wire   [2:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWPROT;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWQOS;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREGION;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWUSER;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WVALID;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WREADY;
wire   [15:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WDATA;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WSTRB;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WLAST;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WID;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WUSER;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARVALID;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARREADY;
wire   [31:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARADDR;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARID;
wire   [31:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARLEN;
wire   [2:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARSIZE;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARBURST;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARLOCK;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARCACHE;
wire   [2:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARPROT;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARQOS;
wire   [3:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARREGION;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARUSER;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RVALID;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RREADY;
wire   [15:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RDATA;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RLAST;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RID;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RUSER;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RRESP;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BVALID;
wire    feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BREADY;
wire   [1:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BRESP;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BID;
wire   [0:0] feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BUSER;
wire   [31:0] feature_Loop_memcpy_featureh_featureHi_U0_featureh1_dout;
wire    feature_Loop_memcpy_featureh_featureHi_U0_featureh1_empty_n;
wire    feature_Loop_memcpy_featureh_featureHi_U0_featureh1_read;
wire   [8:0] feature_Loop_memcpy_featureh_featureHi_U0_featureHist_address0;
wire    feature_Loop_memcpy_featureh_featureHi_U0_featureHist_ce0;
wire   [15:0] feature_Loop_memcpy_featureh_featureHi_U0_featureHist_q0;
wire    ap_sig_hs_continue;
wire    featureHist_i_full_n;
wire    featureHist_i_write;
wire    featureHist_t_empty_n;
wire    featureHist_t_read;
wire    frame_in_channel_U_ap_dummy_ce;
wire   [31:0] frame_in_channel_din;
wire    frame_in_channel_full_n;
wire    frame_in_channel_write;
wire   [31:0] frame_in_channel_dout;
wire    frame_in_channel_empty_n;
wire    frame_in_channel_read;
wire    featureh_channel_U_ap_dummy_ce;
wire   [31:0] featureh_channel_din;
wire    featureh_channel_full_n;
wire    featureh_channel_write;
wire   [31:0] featureh_channel_dout;
wire    featureh_channel_empty_n;
wire    featureh_channel_read;
wire    boundingBoxes_3_loc_channel_U_ap_dummy_ce;
wire   [15:0] boundingBoxes_3_loc_channel_din;
wire    boundingBoxes_3_loc_channel_write;
wire   [15:0] boundingBoxes_3_loc_channel_dout;
wire    boundingBoxes_3_loc_channel_empty_n;
wire    boundingBoxes_3_loc_channel_read;
wire    boundingBoxes_2_loc_channel_U_ap_dummy_ce;
wire   [15:0] boundingBoxes_2_loc_channel_din;
wire    boundingBoxes_2_loc_channel_write;
wire   [15:0] boundingBoxes_2_loc_channel_dout;
wire    boundingBoxes_2_loc_channel_empty_n;
wire    boundingBoxes_2_loc_channel_read;
wire    boundingBoxes_1_loc_channel_U_ap_dummy_ce;
wire   [15:0] boundingBoxes_1_loc_channel_din;
wire    boundingBoxes_1_loc_channel_write;
wire   [15:0] boundingBoxes_1_loc_channel_dout;
wire    boundingBoxes_1_loc_channel_empty_n;
wire    boundingBoxes_1_loc_channel_read;
wire    boundingBoxes_0_loc_channel_U_ap_dummy_ce;
wire   [15:0] boundingBoxes_0_loc_channel_din;
wire    boundingBoxes_0_loc_channel_write;
wire   [15:0] boundingBoxes_0_loc_channel_dout;
wire    boundingBoxes_0_loc_channel_empty_n;
wire    boundingBoxes_0_loc_channel_read;
reg    ap_reg_procdone_feature_Loop_memcpy_boundingBoxes_boun_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_feature_Loop_memset_featureHist_proc1_U0 = 1'b0;
reg    ap_reg_procdone_feature_Loop_memcpy_featureh_featureHi_U0 = 1'b0;
reg    ap_CS;
reg    ap_sig_top_allready;
reg    ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready = 1'b0;
reg    ap_sig_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready;
reg    ap_sig_start_in_feature_Loop_memset_featureHist_proc1_U0_ap_start;
reg    ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready = 1'b0;
reg    ap_sig_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready;
reg    ap_sig_start_in_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start;


feature_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
feature_AXILiteS_s_axi_U(
    .AWVALID( s_axi_AXILiteS_AWVALID ),
    .AWREADY( s_axi_AXILiteS_AWREADY ),
    .AWADDR( s_axi_AXILiteS_AWADDR ),
    .WVALID( s_axi_AXILiteS_WVALID ),
    .WREADY( s_axi_AXILiteS_WREADY ),
    .WDATA( s_axi_AXILiteS_WDATA ),
    .WSTRB( s_axi_AXILiteS_WSTRB ),
    .ARVALID( s_axi_AXILiteS_ARVALID ),
    .ARREADY( s_axi_AXILiteS_ARREADY ),
    .ARADDR( s_axi_AXILiteS_ARADDR ),
    .RVALID( s_axi_AXILiteS_RVALID ),
    .RREADY( s_axi_AXILiteS_RREADY ),
    .RDATA( s_axi_AXILiteS_RDATA ),
    .RRESP( s_axi_AXILiteS_RRESP ),
    .BVALID( s_axi_AXILiteS_BVALID ),
    .BREADY( s_axi_AXILiteS_BREADY ),
    .BRESP( s_axi_AXILiteS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( feature_AXILiteS_s_axi_U_ap_dummy_ce ),
    .frame_in( frame_in ),
    .bounding( bounding ),
    .featureh( featureh )
);

feature_CRTL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CRTL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CRTL_BUS_DATA_WIDTH ))
feature_CRTL_BUS_s_axi_U(
    .AWVALID( s_axi_CRTL_BUS_AWVALID ),
    .AWREADY( s_axi_CRTL_BUS_AWREADY ),
    .AWADDR( s_axi_CRTL_BUS_AWADDR ),
    .WVALID( s_axi_CRTL_BUS_WVALID ),
    .WREADY( s_axi_CRTL_BUS_WREADY ),
    .WDATA( s_axi_CRTL_BUS_WDATA ),
    .WSTRB( s_axi_CRTL_BUS_WSTRB ),
    .ARVALID( s_axi_CRTL_BUS_ARVALID ),
    .ARREADY( s_axi_CRTL_BUS_ARREADY ),
    .ARADDR( s_axi_CRTL_BUS_ARADDR ),
    .RVALID( s_axi_CRTL_BUS_RVALID ),
    .RREADY( s_axi_CRTL_BUS_RREADY ),
    .RDATA( s_axi_CRTL_BUS_RDATA ),
    .RRESP( s_axi_CRTL_BUS_RRESP ),
    .BVALID( s_axi_CRTL_BUS_BVALID ),
    .BREADY( s_axi_CRTL_BUS_BREADY ),
    .BRESP( s_axi_CRTL_BUS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( feature_CRTL_BUS_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle )
);

feature_gmem_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
feature_gmem_m_axi_U(
    .AWVALID( m_axi_gmem_AWVALID ),
    .AWREADY( m_axi_gmem_AWREADY ),
    .AWADDR( m_axi_gmem_AWADDR ),
    .AWID( m_axi_gmem_AWID ),
    .AWLEN( m_axi_gmem_AWLEN ),
    .AWSIZE( m_axi_gmem_AWSIZE ),
    .AWBURST( m_axi_gmem_AWBURST ),
    .AWLOCK( m_axi_gmem_AWLOCK ),
    .AWCACHE( m_axi_gmem_AWCACHE ),
    .AWPROT( m_axi_gmem_AWPROT ),
    .AWQOS( m_axi_gmem_AWQOS ),
    .AWREGION( m_axi_gmem_AWREGION ),
    .AWUSER( m_axi_gmem_AWUSER ),
    .WVALID( m_axi_gmem_WVALID ),
    .WREADY( m_axi_gmem_WREADY ),
    .WDATA( m_axi_gmem_WDATA ),
    .WSTRB( m_axi_gmem_WSTRB ),
    .WLAST( m_axi_gmem_WLAST ),
    .WID( m_axi_gmem_WID ),
    .WUSER( m_axi_gmem_WUSER ),
    .ARVALID( m_axi_gmem_ARVALID ),
    .ARREADY( m_axi_gmem_ARREADY ),
    .ARADDR( m_axi_gmem_ARADDR ),
    .ARID( m_axi_gmem_ARID ),
    .ARLEN( m_axi_gmem_ARLEN ),
    .ARSIZE( m_axi_gmem_ARSIZE ),
    .ARBURST( m_axi_gmem_ARBURST ),
    .ARLOCK( m_axi_gmem_ARLOCK ),
    .ARCACHE( m_axi_gmem_ARCACHE ),
    .ARPROT( m_axi_gmem_ARPROT ),
    .ARQOS( m_axi_gmem_ARQOS ),
    .ARREGION( m_axi_gmem_ARREGION ),
    .ARUSER( m_axi_gmem_ARUSER ),
    .RVALID( m_axi_gmem_RVALID ),
    .RREADY( m_axi_gmem_RREADY ),
    .RDATA( m_axi_gmem_RDATA ),
    .RLAST( m_axi_gmem_RLAST ),
    .RID( m_axi_gmem_RID ),
    .RUSER( m_axi_gmem_RUSER ),
    .RRESP( m_axi_gmem_RRESP ),
    .BVALID( m_axi_gmem_BVALID ),
    .BREADY( m_axi_gmem_BREADY ),
    .BRESP( m_axi_gmem_BRESP ),
    .BID( m_axi_gmem_BID ),
    .BUSER( m_axi_gmem_BUSER ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( feature_gmem_m_axi_U_ap_dummy_ce ),
    .I_ARVALID( gmem_ARVALID ),
    .I_ARREADY( gmem_ARREADY ),
    .I_ARADDR( gmem_ARADDR ),
    .I_ARID( gmem_ARID ),
    .I_ARLEN( gmem_ARLEN ),
    .I_ARSIZE( gmem_ARSIZE ),
    .I_ARLOCK( gmem_ARLOCK ),
    .I_ARCACHE( gmem_ARCACHE ),
    .I_ARQOS( gmem_ARQOS ),
    .I_ARPROT( gmem_ARPROT ),
    .I_ARUSER( gmem_ARUSER ),
    .I_ARBURST( gmem_ARBURST ),
    .I_ARREGION( gmem_ARREGION ),
    .I_RVALID( gmem_RVALID ),
    .I_RREADY( gmem_RREADY ),
    .I_RDATA( gmem_RDATA ),
    .I_RID( gmem_RID ),
    .I_RUSER( gmem_RUSER ),
    .I_RRESP( gmem_RRESP ),
    .I_RLAST( gmem_RLAST ),
    .I_AWVALID( gmem_AWVALID ),
    .I_AWREADY( gmem_AWREADY ),
    .I_AWADDR( gmem_AWADDR ),
    .I_AWID( gmem_AWID ),
    .I_AWLEN( gmem_AWLEN ),
    .I_AWSIZE( gmem_AWSIZE ),
    .I_AWLOCK( gmem_AWLOCK ),
    .I_AWCACHE( gmem_AWCACHE ),
    .I_AWQOS( gmem_AWQOS ),
    .I_AWPROT( gmem_AWPROT ),
    .I_AWUSER( gmem_AWUSER ),
    .I_AWBURST( gmem_AWBURST ),
    .I_AWREGION( gmem_AWREGION ),
    .I_WVALID( gmem_WVALID ),
    .I_WREADY( gmem_WREADY ),
    .I_WDATA( gmem_WDATA ),
    .I_WID( gmem_WID ),
    .I_WUSER( gmem_WUSER ),
    .I_WLAST( gmem_WLAST ),
    .I_WSTRB( gmem_WSTRB ),
    .I_BVALID( gmem_BVALID ),
    .I_BREADY( gmem_BREADY ),
    .I_BRESP( gmem_BRESP ),
    .I_BID( gmem_BID ),
    .I_BUSER( gmem_BUSER )
);

feature_gmem_offset_m_axi #(
    .USER_DW( 16 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_OFFSET_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_OFFSET_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_OFFSET_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_OFFSET_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_OFFSET_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_OFFSET_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_OFFSET_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_OFFSET_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_OFFSET_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_OFFSET_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_OFFSET_CACHE_VALUE ))
feature_gmem_offset_m_axi_U(
    .AWVALID( m_axi_gmem_offset_AWVALID ),
    .AWREADY( m_axi_gmem_offset_AWREADY ),
    .AWADDR( m_axi_gmem_offset_AWADDR ),
    .AWID( m_axi_gmem_offset_AWID ),
    .AWLEN( m_axi_gmem_offset_AWLEN ),
    .AWSIZE( m_axi_gmem_offset_AWSIZE ),
    .AWBURST( m_axi_gmem_offset_AWBURST ),
    .AWLOCK( m_axi_gmem_offset_AWLOCK ),
    .AWCACHE( m_axi_gmem_offset_AWCACHE ),
    .AWPROT( m_axi_gmem_offset_AWPROT ),
    .AWQOS( m_axi_gmem_offset_AWQOS ),
    .AWREGION( m_axi_gmem_offset_AWREGION ),
    .AWUSER( m_axi_gmem_offset_AWUSER ),
    .WVALID( m_axi_gmem_offset_WVALID ),
    .WREADY( m_axi_gmem_offset_WREADY ),
    .WDATA( m_axi_gmem_offset_WDATA ),
    .WSTRB( m_axi_gmem_offset_WSTRB ),
    .WLAST( m_axi_gmem_offset_WLAST ),
    .WID( m_axi_gmem_offset_WID ),
    .WUSER( m_axi_gmem_offset_WUSER ),
    .ARVALID( m_axi_gmem_offset_ARVALID ),
    .ARREADY( m_axi_gmem_offset_ARREADY ),
    .ARADDR( m_axi_gmem_offset_ARADDR ),
    .ARID( m_axi_gmem_offset_ARID ),
    .ARLEN( m_axi_gmem_offset_ARLEN ),
    .ARSIZE( m_axi_gmem_offset_ARSIZE ),
    .ARBURST( m_axi_gmem_offset_ARBURST ),
    .ARLOCK( m_axi_gmem_offset_ARLOCK ),
    .ARCACHE( m_axi_gmem_offset_ARCACHE ),
    .ARPROT( m_axi_gmem_offset_ARPROT ),
    .ARQOS( m_axi_gmem_offset_ARQOS ),
    .ARREGION( m_axi_gmem_offset_ARREGION ),
    .ARUSER( m_axi_gmem_offset_ARUSER ),
    .RVALID( m_axi_gmem_offset_RVALID ),
    .RREADY( m_axi_gmem_offset_RREADY ),
    .RDATA( m_axi_gmem_offset_RDATA ),
    .RLAST( m_axi_gmem_offset_RLAST ),
    .RID( m_axi_gmem_offset_RID ),
    .RUSER( m_axi_gmem_offset_RUSER ),
    .RRESP( m_axi_gmem_offset_RRESP ),
    .BVALID( m_axi_gmem_offset_BVALID ),
    .BREADY( m_axi_gmem_offset_BREADY ),
    .BRESP( m_axi_gmem_offset_BRESP ),
    .BID( m_axi_gmem_offset_BID ),
    .BUSER( m_axi_gmem_offset_BUSER ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( feature_gmem_offset_m_axi_U_ap_dummy_ce ),
    .I_ARVALID( gmem_offset_ARVALID ),
    .I_ARREADY( gmem_offset_ARREADY ),
    .I_ARADDR( gmem_offset_ARADDR ),
    .I_ARID( gmem_offset_ARID ),
    .I_ARLEN( gmem_offset_ARLEN ),
    .I_ARSIZE( gmem_offset_ARSIZE ),
    .I_ARLOCK( gmem_offset_ARLOCK ),
    .I_ARCACHE( gmem_offset_ARCACHE ),
    .I_ARQOS( gmem_offset_ARQOS ),
    .I_ARPROT( gmem_offset_ARPROT ),
    .I_ARUSER( gmem_offset_ARUSER ),
    .I_ARBURST( gmem_offset_ARBURST ),
    .I_ARREGION( gmem_offset_ARREGION ),
    .I_RVALID( gmem_offset_RVALID ),
    .I_RREADY( gmem_offset_RREADY ),
    .I_RDATA( gmem_offset_RDATA ),
    .I_RID( gmem_offset_RID ),
    .I_RUSER( gmem_offset_RUSER ),
    .I_RRESP( gmem_offset_RRESP ),
    .I_RLAST( gmem_offset_RLAST ),
    .I_AWVALID( gmem_offset_AWVALID ),
    .I_AWREADY( gmem_offset_AWREADY ),
    .I_AWADDR( gmem_offset_AWADDR ),
    .I_AWID( gmem_offset_AWID ),
    .I_AWLEN( gmem_offset_AWLEN ),
    .I_AWSIZE( gmem_offset_AWSIZE ),
    .I_AWLOCK( gmem_offset_AWLOCK ),
    .I_AWCACHE( gmem_offset_AWCACHE ),
    .I_AWQOS( gmem_offset_AWQOS ),
    .I_AWPROT( gmem_offset_AWPROT ),
    .I_AWUSER( gmem_offset_AWUSER ),
    .I_AWBURST( gmem_offset_AWBURST ),
    .I_AWREGION( gmem_offset_AWREGION ),
    .I_WVALID( gmem_offset_WVALID ),
    .I_WREADY( gmem_offset_WREADY ),
    .I_WDATA( gmem_offset_WDATA ),
    .I_WID( gmem_offset_WID ),
    .I_WUSER( gmem_offset_WUSER ),
    .I_WLAST( gmem_offset_WLAST ),
    .I_WSTRB( gmem_offset_WSTRB ),
    .I_BVALID( gmem_offset_BVALID ),
    .I_BREADY( gmem_offset_BREADY ),
    .I_BRESP( gmem_offset_BRESP ),
    .I_BID( gmem_offset_BID ),
    .I_BUSER( gmem_offset_BUSER )
);

feature_featureHist #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
featureHist_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .i_address0( featureHist_i_address0 ),
    .i_ce0( featureHist_i_ce0 ),
    .i_we0( featureHist_i_we0 ),
    .i_d0( featureHist_i_d0 ),
    .i_q0( featureHist_i_q0 ),
    .i_address1( featureHist_i_address1 ),
    .i_ce1( featureHist_i_ce1 ),
    .i_we1( featureHist_i_we1 ),
    .i_d1( featureHist_i_d1 ),
    .i_q1( featureHist_i_q1 ),
    .t_address0( featureHist_t_address0 ),
    .t_ce0( featureHist_t_ce0 ),
    .t_we0( featureHist_t_we0 ),
    .t_d0( featureHist_t_d0 ),
    .t_q0( featureHist_t_q0 ),
    .t_address1( featureHist_t_address1 ),
    .t_ce1( featureHist_t_ce1 ),
    .t_we1( featureHist_t_we1 ),
    .t_d1( featureHist_t_d1 ),
    .t_q1( featureHist_t_q1 ),
    .i_ce( featureHist_U_ap_dummy_ce ),
    .t_ce( featureHist_U_ap_dummy_ce ),
    .i_full_n( featureHist_i_full_n ),
    .i_write( featureHist_i_write ),
    .t_empty_n( featureHist_t_empty_n ),
    .t_read( featureHist_t_read )
);

feature_Loop_memcpy_boundingBoxes_boun feature_Loop_memcpy_boundingBoxes_boun_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start ),
    .ap_done( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done ),
    .ap_continue( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue ),
    .ap_idle( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_idle ),
    .ap_ready( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready ),
    .m_axi_bounding_AWVALID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWVALID ),
    .m_axi_bounding_AWREADY( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWREADY ),
    .m_axi_bounding_AWADDR( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWADDR ),
    .m_axi_bounding_AWID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWID ),
    .m_axi_bounding_AWLEN( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWLEN ),
    .m_axi_bounding_AWSIZE( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWSIZE ),
    .m_axi_bounding_AWBURST( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWBURST ),
    .m_axi_bounding_AWLOCK( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWLOCK ),
    .m_axi_bounding_AWCACHE( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWCACHE ),
    .m_axi_bounding_AWPROT( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWPROT ),
    .m_axi_bounding_AWQOS( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWQOS ),
    .m_axi_bounding_AWREGION( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWREGION ),
    .m_axi_bounding_AWUSER( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWUSER ),
    .m_axi_bounding_WVALID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WVALID ),
    .m_axi_bounding_WREADY( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WREADY ),
    .m_axi_bounding_WDATA( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WDATA ),
    .m_axi_bounding_WSTRB( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WSTRB ),
    .m_axi_bounding_WLAST( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WLAST ),
    .m_axi_bounding_WID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WID ),
    .m_axi_bounding_WUSER( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WUSER ),
    .m_axi_bounding_ARVALID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARVALID ),
    .m_axi_bounding_ARREADY( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREADY ),
    .m_axi_bounding_ARADDR( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARADDR ),
    .m_axi_bounding_ARID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARID ),
    .m_axi_bounding_ARLEN( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLEN ),
    .m_axi_bounding_ARSIZE( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARSIZE ),
    .m_axi_bounding_ARBURST( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARBURST ),
    .m_axi_bounding_ARLOCK( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLOCK ),
    .m_axi_bounding_ARCACHE( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARCACHE ),
    .m_axi_bounding_ARPROT( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARPROT ),
    .m_axi_bounding_ARQOS( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARQOS ),
    .m_axi_bounding_ARREGION( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREGION ),
    .m_axi_bounding_ARUSER( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARUSER ),
    .m_axi_bounding_RVALID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RVALID ),
    .m_axi_bounding_RREADY( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RREADY ),
    .m_axi_bounding_RDATA( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RDATA ),
    .m_axi_bounding_RLAST( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RLAST ),
    .m_axi_bounding_RID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RID ),
    .m_axi_bounding_RUSER( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RUSER ),
    .m_axi_bounding_RRESP( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RRESP ),
    .m_axi_bounding_BVALID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BVALID ),
    .m_axi_bounding_BREADY( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BREADY ),
    .m_axi_bounding_BRESP( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BRESP ),
    .m_axi_bounding_BID( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BID ),
    .m_axi_bounding_BUSER( feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BUSER ),
    .bounding1( feature_Loop_memcpy_boundingBoxes_boun_U0_bounding1 ),
    .frame_in( feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in ),
    .featureh( feature_Loop_memcpy_boundingBoxes_boun_U0_featureh ),
    .frame_in_out_din( feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_din ),
    .frame_in_out_full_n( feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_full_n ),
    .frame_in_out_write( feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_write ),
    .featureh_out_din( feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_din ),
    .featureh_out_full_n( feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_full_n ),
    .featureh_out_write( feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_write ),
    .ap_return_0( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_0 ),
    .ap_return_1( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_1 ),
    .ap_return_2( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_2 ),
    .ap_return_3( feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_3 )
);

feature_Loop_memset_featureHist_proc1 feature_Loop_memset_featureHist_proc1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( feature_Loop_memset_featureHist_proc1_U0_ap_start ),
    .ap_done( feature_Loop_memset_featureHist_proc1_U0_ap_done ),
    .ap_continue( feature_Loop_memset_featureHist_proc1_U0_ap_continue ),
    .ap_idle( feature_Loop_memset_featureHist_proc1_U0_ap_idle ),
    .ap_ready( feature_Loop_memset_featureHist_proc1_U0_ap_ready ),
    .featureHist_address0( feature_Loop_memset_featureHist_proc1_U0_featureHist_address0 ),
    .featureHist_ce0( feature_Loop_memset_featureHist_proc1_U0_featureHist_ce0 ),
    .featureHist_we0( feature_Loop_memset_featureHist_proc1_U0_featureHist_we0 ),
    .featureHist_d0( feature_Loop_memset_featureHist_proc1_U0_featureHist_d0 ),
    .featureHist_q0( feature_Loop_memset_featureHist_proc1_U0_featureHist_q0 ),
    .featureHist_address1( feature_Loop_memset_featureHist_proc1_U0_featureHist_address1 ),
    .featureHist_ce1( feature_Loop_memset_featureHist_proc1_U0_featureHist_ce1 ),
    .featureHist_we1( feature_Loop_memset_featureHist_proc1_U0_featureHist_we1 ),
    .featureHist_d1( feature_Loop_memset_featureHist_proc1_U0_featureHist_d1 ),
    .featureHist_q1( feature_Loop_memset_featureHist_proc1_U0_featureHist_q1 ),
    .m_axi_frame_in_AWVALID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWVALID ),
    .m_axi_frame_in_AWREADY( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWREADY ),
    .m_axi_frame_in_AWADDR( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWADDR ),
    .m_axi_frame_in_AWID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWID ),
    .m_axi_frame_in_AWLEN( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWLEN ),
    .m_axi_frame_in_AWSIZE( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWSIZE ),
    .m_axi_frame_in_AWBURST( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWBURST ),
    .m_axi_frame_in_AWLOCK( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWLOCK ),
    .m_axi_frame_in_AWCACHE( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWCACHE ),
    .m_axi_frame_in_AWPROT( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWPROT ),
    .m_axi_frame_in_AWQOS( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWQOS ),
    .m_axi_frame_in_AWREGION( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWREGION ),
    .m_axi_frame_in_AWUSER( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWUSER ),
    .m_axi_frame_in_WVALID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WVALID ),
    .m_axi_frame_in_WREADY( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WREADY ),
    .m_axi_frame_in_WDATA( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WDATA ),
    .m_axi_frame_in_WSTRB( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WSTRB ),
    .m_axi_frame_in_WLAST( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WLAST ),
    .m_axi_frame_in_WID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WID ),
    .m_axi_frame_in_WUSER( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WUSER ),
    .m_axi_frame_in_ARVALID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARVALID ),
    .m_axi_frame_in_ARREADY( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREADY ),
    .m_axi_frame_in_ARADDR( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARADDR ),
    .m_axi_frame_in_ARID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARID ),
    .m_axi_frame_in_ARLEN( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLEN ),
    .m_axi_frame_in_ARSIZE( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARSIZE ),
    .m_axi_frame_in_ARBURST( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARBURST ),
    .m_axi_frame_in_ARLOCK( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLOCK ),
    .m_axi_frame_in_ARCACHE( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARCACHE ),
    .m_axi_frame_in_ARPROT( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARPROT ),
    .m_axi_frame_in_ARQOS( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARQOS ),
    .m_axi_frame_in_ARREGION( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREGION ),
    .m_axi_frame_in_ARUSER( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARUSER ),
    .m_axi_frame_in_RVALID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RVALID ),
    .m_axi_frame_in_RREADY( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RREADY ),
    .m_axi_frame_in_RDATA( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RDATA ),
    .m_axi_frame_in_RLAST( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RLAST ),
    .m_axi_frame_in_RID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RID ),
    .m_axi_frame_in_RUSER( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RUSER ),
    .m_axi_frame_in_RRESP( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RRESP ),
    .m_axi_frame_in_BVALID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BVALID ),
    .m_axi_frame_in_BREADY( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BREADY ),
    .m_axi_frame_in_BRESP( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BRESP ),
    .m_axi_frame_in_BID( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BID ),
    .m_axi_frame_in_BUSER( feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BUSER ),
    .frame_in1_dout( feature_Loop_memset_featureHist_proc1_U0_frame_in1_dout ),
    .frame_in1_empty_n( feature_Loop_memset_featureHist_proc1_U0_frame_in1_empty_n ),
    .frame_in1_read( feature_Loop_memset_featureHist_proc1_U0_frame_in1_read ),
    .p_read( feature_Loop_memset_featureHist_proc1_U0_p_read ),
    .p_read1( feature_Loop_memset_featureHist_proc1_U0_p_read1 ),
    .p_read2( feature_Loop_memset_featureHist_proc1_U0_p_read2 ),
    .p_read3( feature_Loop_memset_featureHist_proc1_U0_p_read3 )
);

feature_Loop_memcpy_featureh_featureHi feature_Loop_memcpy_featureh_featureHi_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( feature_Loop_memcpy_featureh_featureHi_U0_ap_start ),
    .ap_done( feature_Loop_memcpy_featureh_featureHi_U0_ap_done ),
    .ap_continue( feature_Loop_memcpy_featureh_featureHi_U0_ap_continue ),
    .ap_idle( feature_Loop_memcpy_featureh_featureHi_U0_ap_idle ),
    .ap_ready( feature_Loop_memcpy_featureh_featureHi_U0_ap_ready ),
    .m_axi_featureh_AWVALID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWVALID ),
    .m_axi_featureh_AWREADY( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREADY ),
    .m_axi_featureh_AWADDR( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWADDR ),
    .m_axi_featureh_AWID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWID ),
    .m_axi_featureh_AWLEN( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLEN ),
    .m_axi_featureh_AWSIZE( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWSIZE ),
    .m_axi_featureh_AWBURST( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWBURST ),
    .m_axi_featureh_AWLOCK( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLOCK ),
    .m_axi_featureh_AWCACHE( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWCACHE ),
    .m_axi_featureh_AWPROT( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWPROT ),
    .m_axi_featureh_AWQOS( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWQOS ),
    .m_axi_featureh_AWREGION( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREGION ),
    .m_axi_featureh_AWUSER( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWUSER ),
    .m_axi_featureh_WVALID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WVALID ),
    .m_axi_featureh_WREADY( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WREADY ),
    .m_axi_featureh_WDATA( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WDATA ),
    .m_axi_featureh_WSTRB( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WSTRB ),
    .m_axi_featureh_WLAST( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WLAST ),
    .m_axi_featureh_WID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WID ),
    .m_axi_featureh_WUSER( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WUSER ),
    .m_axi_featureh_ARVALID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARVALID ),
    .m_axi_featureh_ARREADY( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARREADY ),
    .m_axi_featureh_ARADDR( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARADDR ),
    .m_axi_featureh_ARID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARID ),
    .m_axi_featureh_ARLEN( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARLEN ),
    .m_axi_featureh_ARSIZE( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARSIZE ),
    .m_axi_featureh_ARBURST( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARBURST ),
    .m_axi_featureh_ARLOCK( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARLOCK ),
    .m_axi_featureh_ARCACHE( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARCACHE ),
    .m_axi_featureh_ARPROT( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARPROT ),
    .m_axi_featureh_ARQOS( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARQOS ),
    .m_axi_featureh_ARREGION( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARREGION ),
    .m_axi_featureh_ARUSER( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARUSER ),
    .m_axi_featureh_RVALID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RVALID ),
    .m_axi_featureh_RREADY( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RREADY ),
    .m_axi_featureh_RDATA( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RDATA ),
    .m_axi_featureh_RLAST( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RLAST ),
    .m_axi_featureh_RID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RID ),
    .m_axi_featureh_RUSER( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RUSER ),
    .m_axi_featureh_RRESP( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RRESP ),
    .m_axi_featureh_BVALID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BVALID ),
    .m_axi_featureh_BREADY( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BREADY ),
    .m_axi_featureh_BRESP( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BRESP ),
    .m_axi_featureh_BID( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BID ),
    .m_axi_featureh_BUSER( feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BUSER ),
    .featureh1_dout( feature_Loop_memcpy_featureh_featureHi_U0_featureh1_dout ),
    .featureh1_empty_n( feature_Loop_memcpy_featureh_featureHi_U0_featureh1_empty_n ),
    .featureh1_read( feature_Loop_memcpy_featureh_featureHi_U0_featureh1_read ),
    .featureHist_address0( feature_Loop_memcpy_featureh_featureHi_U0_featureHist_address0 ),
    .featureHist_ce0( feature_Loop_memcpy_featureh_featureHi_U0_featureHist_ce0 ),
    .featureHist_q0( feature_Loop_memcpy_featureh_featureHi_U0_featureHist_q0 )
);

FIFO_feature_frame_in_channel frame_in_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( frame_in_channel_U_ap_dummy_ce ),
    .if_write_ce( frame_in_channel_U_ap_dummy_ce ),
    .if_din( frame_in_channel_din ),
    .if_full_n( frame_in_channel_full_n ),
    .if_write( frame_in_channel_write ),
    .if_dout( frame_in_channel_dout ),
    .if_empty_n( frame_in_channel_empty_n ),
    .if_read( frame_in_channel_read )
);

FIFO_feature_featureh_channel featureh_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( featureh_channel_U_ap_dummy_ce ),
    .if_write_ce( featureh_channel_U_ap_dummy_ce ),
    .if_din( featureh_channel_din ),
    .if_full_n( featureh_channel_full_n ),
    .if_write( featureh_channel_write ),
    .if_dout( featureh_channel_dout ),
    .if_empty_n( featureh_channel_empty_n ),
    .if_read( featureh_channel_read )
);

FIFO_feature_boundingBoxes_3_loc_channel boundingBoxes_3_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( boundingBoxes_3_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( boundingBoxes_3_loc_channel_U_ap_dummy_ce ),
    .if_din( boundingBoxes_3_loc_channel_din ),
    .if_full_n( boundingBoxes_3_loc_channel_full_n ),
    .if_write( boundingBoxes_3_loc_channel_write ),
    .if_dout( boundingBoxes_3_loc_channel_dout ),
    .if_empty_n( boundingBoxes_3_loc_channel_empty_n ),
    .if_read( boundingBoxes_3_loc_channel_read )
);

FIFO_feature_boundingBoxes_2_loc_channel boundingBoxes_2_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( boundingBoxes_2_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( boundingBoxes_2_loc_channel_U_ap_dummy_ce ),
    .if_din( boundingBoxes_2_loc_channel_din ),
    .if_full_n( boundingBoxes_2_loc_channel_full_n ),
    .if_write( boundingBoxes_2_loc_channel_write ),
    .if_dout( boundingBoxes_2_loc_channel_dout ),
    .if_empty_n( boundingBoxes_2_loc_channel_empty_n ),
    .if_read( boundingBoxes_2_loc_channel_read )
);

FIFO_feature_boundingBoxes_1_loc_channel boundingBoxes_1_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( boundingBoxes_1_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( boundingBoxes_1_loc_channel_U_ap_dummy_ce ),
    .if_din( boundingBoxes_1_loc_channel_din ),
    .if_full_n( boundingBoxes_1_loc_channel_full_n ),
    .if_write( boundingBoxes_1_loc_channel_write ),
    .if_dout( boundingBoxes_1_loc_channel_dout ),
    .if_empty_n( boundingBoxes_1_loc_channel_empty_n ),
    .if_read( boundingBoxes_1_loc_channel_read )
);

FIFO_feature_boundingBoxes_0_loc_channel boundingBoxes_0_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( boundingBoxes_0_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( boundingBoxes_0_loc_channel_U_ap_dummy_ce ),
    .if_din( boundingBoxes_0_loc_channel_din ),
    .if_full_n( boundingBoxes_0_loc_channel_full_n ),
    .if_write( boundingBoxes_0_loc_channel_write ),
    .if_dout( boundingBoxes_0_loc_channel_dout ),
    .if_empty_n( boundingBoxes_0_loc_channel_empty_n ),
    .if_read( boundingBoxes_0_loc_channel_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_feature_Loop_memcpy_boundingBoxes_boun_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_feature_Loop_memcpy_boundingBoxes_boun_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_feature_Loop_memcpy_boundingBoxes_boun_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done)) begin
            ap_reg_procdone_feature_Loop_memcpy_boundingBoxes_boun_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_feature_Loop_memcpy_featureh_featureHi_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_feature_Loop_memcpy_featureh_featureHi_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_feature_Loop_memcpy_featureh_featureHi_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == feature_Loop_memcpy_featureh_featureHi_U0_ap_done)) begin
            ap_reg_procdone_feature_Loop_memcpy_featureh_featureHi_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_feature_Loop_memset_featureHist_proc1_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_feature_Loop_memset_featureHist_proc1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_feature_Loop_memset_featureHist_proc1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == feature_Loop_memset_featureHist_proc1_U0_ap_done)) begin
            ap_reg_procdone_feature_Loop_memset_featureHist_proc1_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_boundingBoxes_0_loc_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_boundingBoxes_0_loc_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue))) begin
            ap_reg_ready_boundingBoxes_0_loc_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == boundingBoxes_0_loc_channel_full_n))) begin
            ap_reg_ready_boundingBoxes_0_loc_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_boundingBoxes_1_loc_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_boundingBoxes_1_loc_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue))) begin
            ap_reg_ready_boundingBoxes_1_loc_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == boundingBoxes_1_loc_channel_full_n))) begin
            ap_reg_ready_boundingBoxes_1_loc_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_boundingBoxes_2_loc_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_boundingBoxes_2_loc_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue))) begin
            ap_reg_ready_boundingBoxes_2_loc_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == boundingBoxes_2_loc_channel_full_n))) begin
            ap_reg_ready_boundingBoxes_2_loc_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_boundingBoxes_3_loc_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_boundingBoxes_3_loc_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue))) begin
            ap_reg_ready_boundingBoxes_3_loc_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done) & (ap_const_logic_1 == boundingBoxes_3_loc_channel_full_n))) begin
            ap_reg_ready_boundingBoxes_3_loc_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready)) begin
            ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == feature_Loop_memset_featureHist_proc1_U0_ap_ready)) begin
            ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done or ap_reg_ready_boundingBoxes_0_loc_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_boundingBoxes_0_loc_channel_full_n)) begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_0_loc_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_0_loc_channel = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done;
    end
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done or ap_reg_ready_boundingBoxes_1_loc_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_boundingBoxes_1_loc_channel_full_n)) begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_1_loc_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_1_loc_channel = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done;
    end
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done or ap_reg_ready_boundingBoxes_2_loc_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_boundingBoxes_2_loc_channel_full_n)) begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_2_loc_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_2_loc_channel = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done;
    end
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done or ap_reg_ready_boundingBoxes_3_loc_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_boundingBoxes_3_loc_channel_full_n)) begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_3_loc_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_3_loc_channel = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_done;
    end
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_idle or feature_Loop_memset_featureHist_proc1_U0_ap_idle or feature_Loop_memcpy_featureh_featureHi_U0_ap_idle or featureHist_t_empty_n or boundingBoxes_3_loc_channel_empty_n or boundingBoxes_2_loc_channel_empty_n or boundingBoxes_1_loc_channel_empty_n or boundingBoxes_0_loc_channel_empty_n) begin
    if (((ap_const_logic_1 == feature_Loop_memcpy_boundingBoxes_boun_U0_ap_idle) & (ap_const_logic_1 == feature_Loop_memset_featureHist_proc1_U0_ap_idle) & (ap_const_logic_1 == feature_Loop_memcpy_featureh_featureHi_U0_ap_idle) & (ap_const_logic_0 == boundingBoxes_3_loc_channel_empty_n) & (ap_const_logic_0 == boundingBoxes_2_loc_channel_empty_n) & (ap_const_logic_0 == boundingBoxes_1_loc_channel_empty_n) & (ap_const_logic_0 == boundingBoxes_0_loc_channel_empty_n) & (ap_const_logic_0 == featureHist_t_empty_n))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (feature_Loop_memcpy_featureh_featureHi_U0_ap_done) begin
    if ((ap_const_logic_1 == feature_Loop_memcpy_featureh_featureHi_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

always @ (boundingBoxes_0_loc_channel_full_n or ap_reg_ready_boundingBoxes_0_loc_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_boundingBoxes_0_loc_channel_full_n)) begin
        ap_sig_ready_boundingBoxes_0_loc_channel_full_n = boundingBoxes_0_loc_channel_full_n;
    end else begin
        ap_sig_ready_boundingBoxes_0_loc_channel_full_n = ap_const_logic_1;
    end
end

always @ (boundingBoxes_1_loc_channel_full_n or ap_reg_ready_boundingBoxes_1_loc_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_boundingBoxes_1_loc_channel_full_n)) begin
        ap_sig_ready_boundingBoxes_1_loc_channel_full_n = boundingBoxes_1_loc_channel_full_n;
    end else begin
        ap_sig_ready_boundingBoxes_1_loc_channel_full_n = ap_const_logic_1;
    end
end

always @ (boundingBoxes_2_loc_channel_full_n or ap_reg_ready_boundingBoxes_2_loc_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_boundingBoxes_2_loc_channel_full_n)) begin
        ap_sig_ready_boundingBoxes_2_loc_channel_full_n = boundingBoxes_2_loc_channel_full_n;
    end else begin
        ap_sig_ready_boundingBoxes_2_loc_channel_full_n = ap_const_logic_1;
    end
end

always @ (boundingBoxes_3_loc_channel_full_n or ap_reg_ready_boundingBoxes_3_loc_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_boundingBoxes_3_loc_channel_full_n)) begin
        ap_sig_ready_boundingBoxes_3_loc_channel_full_n = boundingBoxes_3_loc_channel_full_n;
    end else begin
        ap_sig_ready_boundingBoxes_3_loc_channel_full_n = ap_const_logic_1;
    end
end

always @ (feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready or ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready) begin
    if ((ap_const_logic_0 == ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready)) begin
        ap_sig_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready;
    end else begin
        ap_sig_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready = ap_const_logic_1;
    end
end

always @ (feature_Loop_memset_featureHist_proc1_U0_ap_ready or ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready) begin
    if ((ap_const_logic_0 == ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready)) begin
        ap_sig_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready = feature_Loop_memset_featureHist_proc1_U0_ap_ready;
    end else begin
        ap_sig_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready = ap_const_logic_1;
    end
end

always @ (ap_start or ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready) begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready))) begin
        ap_sig_start_in_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start = ap_const_logic_0;
    end
end

always @ (ap_start or ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready) begin
    if (((ap_const_logic_0 == ap_reg_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready) & (ap_const_logic_1 == ap_start))) begin
        ap_sig_start_in_feature_Loop_memset_featureHist_proc1_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_feature_Loop_memset_featureHist_proc1_U0_ap_start = ap_const_logic_0;
    end
end

always @ (ap_sig_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready or ap_sig_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready) begin
    if (((ap_const_logic_1 == ap_sig_ready_feature_Loop_memset_featureHist_proc1_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_ready))) begin
        ap_sig_top_allready = ap_const_logic_1;
    end else begin
        ap_sig_top_allready = ap_const_logic_0;
    end
end

always @ (ap_sig_ready_boundingBoxes_0_loc_channel_full_n or ap_sig_ready_boundingBoxes_2_loc_channel_full_n or ap_sig_ready_boundingBoxes_3_loc_channel_full_n or ap_sig_ready_boundingBoxes_1_loc_channel_full_n) begin
    if (((ap_const_logic_1 == ap_sig_ready_boundingBoxes_0_loc_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_boundingBoxes_2_loc_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_boundingBoxes_3_loc_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_boundingBoxes_1_loc_channel_full_n))) begin
        feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue = ap_const_logic_1;
    end else begin
        feature_Loop_memcpy_boundingBoxes_boun_U0_ap_continue = ap_const_logic_0;
    end
end

assign ap_chn_write_feature_Loop_memset_featureHist_proc1_U0_featureHist = feature_Loop_memset_featureHist_proc1_U0_ap_done;

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign boundingBoxes_0_loc_channel_U_ap_dummy_ce = ap_const_logic_1;

assign boundingBoxes_0_loc_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_3;

assign boundingBoxes_0_loc_channel_read = feature_Loop_memset_featureHist_proc1_U0_ap_ready;

assign boundingBoxes_0_loc_channel_write = ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_0_loc_channel;

assign boundingBoxes_1_loc_channel_U_ap_dummy_ce = ap_const_logic_1;

assign boundingBoxes_1_loc_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_2;

assign boundingBoxes_1_loc_channel_read = feature_Loop_memset_featureHist_proc1_U0_ap_ready;

assign boundingBoxes_1_loc_channel_write = ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_1_loc_channel;

assign boundingBoxes_2_loc_channel_U_ap_dummy_ce = ap_const_logic_1;

assign boundingBoxes_2_loc_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_1;

assign boundingBoxes_2_loc_channel_read = feature_Loop_memset_featureHist_proc1_U0_ap_ready;

assign boundingBoxes_2_loc_channel_write = ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_2_loc_channel;

assign boundingBoxes_3_loc_channel_U_ap_dummy_ce = ap_const_logic_1;

assign boundingBoxes_3_loc_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_ap_return_0;

assign boundingBoxes_3_loc_channel_read = feature_Loop_memset_featureHist_proc1_U0_ap_ready;

assign boundingBoxes_3_loc_channel_write = ap_chn_write_feature_Loop_memcpy_boundingBoxes_boun_U0_boundingBoxes_3_loc_channel;

assign featureHist_U_ap_dummy_ce = ap_const_logic_1;

assign featureHist_i_address0 = feature_Loop_memset_featureHist_proc1_U0_featureHist_address0;

assign featureHist_i_address1 = feature_Loop_memset_featureHist_proc1_U0_featureHist_address1;

assign featureHist_i_ce0 = feature_Loop_memset_featureHist_proc1_U0_featureHist_ce0;

assign featureHist_i_ce1 = feature_Loop_memset_featureHist_proc1_U0_featureHist_ce1;

assign featureHist_i_d0 = feature_Loop_memset_featureHist_proc1_U0_featureHist_d0;

assign featureHist_i_d1 = feature_Loop_memset_featureHist_proc1_U0_featureHist_d1;

assign featureHist_i_we0 = feature_Loop_memset_featureHist_proc1_U0_featureHist_we0;

assign featureHist_i_we1 = feature_Loop_memset_featureHist_proc1_U0_featureHist_we1;

assign featureHist_i_write = feature_Loop_memset_featureHist_proc1_U0_ap_done;

assign featureHist_t_address0 = feature_Loop_memcpy_featureh_featureHi_U0_featureHist_address0;

assign featureHist_t_address1 = ap_const_lv9_0;

assign featureHist_t_ce0 = feature_Loop_memcpy_featureh_featureHi_U0_featureHist_ce0;

assign featureHist_t_ce1 = ap_const_logic_0;

assign featureHist_t_d0 = ap_const_lv16_0;

assign featureHist_t_d1 = ap_const_lv16_0;

assign featureHist_t_read = feature_Loop_memcpy_featureh_featureHi_U0_ap_ready;

assign featureHist_t_we0 = ap_const_logic_0;

assign featureHist_t_we1 = ap_const_logic_0;

assign feature_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign feature_CRTL_BUS_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start = ap_sig_start_in_feature_Loop_memcpy_boundingBoxes_boun_U0_ap_start;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_bounding1 = bounding;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_featureh = featureh;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_full_n = featureh_channel_full_n;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in = frame_in;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_full_n = frame_in_channel_full_n;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREADY = gmem_offset_ARREADY;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_AWREADY = ap_const_logic_0;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BID = ap_const_lv1_0;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BRESP = ap_const_lv2_0;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BUSER = ap_const_lv1_0;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_BVALID = ap_const_logic_0;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RDATA = gmem_offset_RDATA;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RID = gmem_offset_RID;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RLAST = gmem_offset_RLAST;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RRESP = gmem_offset_RRESP;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RUSER = gmem_offset_RUSER;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RVALID = gmem_offset_RVALID;

assign feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_WREADY = ap_const_logic_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_ap_continue = ap_sig_hs_continue;

assign feature_Loop_memcpy_featureh_featureHi_U0_ap_start = featureHist_t_empty_n;

assign feature_Loop_memcpy_featureh_featureHi_U0_featureHist_q0 = featureHist_t_q0;

assign feature_Loop_memcpy_featureh_featureHi_U0_featureh1_dout = featureh_channel_dout;

assign feature_Loop_memcpy_featureh_featureHi_U0_featureh1_empty_n = featureh_channel_empty_n;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_ARREADY = ap_const_logic_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREADY = gmem_offset_AWREADY;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BID = gmem_offset_BID;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BRESP = gmem_offset_BRESP;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BUSER = gmem_offset_BUSER;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BVALID = gmem_offset_BVALID;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RDATA = ap_const_lv16_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RID = ap_const_lv1_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RLAST = ap_const_logic_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RRESP = ap_const_lv2_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RUSER = ap_const_lv1_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_RVALID = ap_const_logic_0;

assign feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WREADY = gmem_offset_WREADY;

assign feature_Loop_memset_featureHist_proc1_U0_ap_continue = feature_Loop_memset_featureHist_proc1_U0_featureHist_pipo_status;

assign feature_Loop_memset_featureHist_proc1_U0_ap_start = (boundingBoxes_3_loc_channel_empty_n & boundingBoxes_2_loc_channel_empty_n & boundingBoxes_1_loc_channel_empty_n & boundingBoxes_0_loc_channel_empty_n & ap_sig_start_in_feature_Loop_memset_featureHist_proc1_U0_ap_start);

assign feature_Loop_memset_featureHist_proc1_U0_featureHist_pipo_status = featureHist_i_full_n;

assign feature_Loop_memset_featureHist_proc1_U0_featureHist_q0 = featureHist_i_q0;

assign feature_Loop_memset_featureHist_proc1_U0_featureHist_q1 = featureHist_i_q1;

assign feature_Loop_memset_featureHist_proc1_U0_frame_in1_dout = frame_in_channel_dout;

assign feature_Loop_memset_featureHist_proc1_U0_frame_in1_empty_n = frame_in_channel_empty_n;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREADY = gmem_ARREADY;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_AWREADY = ap_const_logic_0;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BID = ap_const_lv1_0;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BRESP = ap_const_lv2_0;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BUSER = ap_const_lv1_0;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_BVALID = ap_const_logic_0;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RDATA = gmem_RDATA;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RID = gmem_RID;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RLAST = gmem_RLAST;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RRESP = gmem_RRESP;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RUSER = gmem_RUSER;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RVALID = gmem_RVALID;

assign feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_WREADY = ap_const_logic_0;

assign feature_Loop_memset_featureHist_proc1_U0_p_read = boundingBoxes_0_loc_channel_dout;

assign feature_Loop_memset_featureHist_proc1_U0_p_read1 = boundingBoxes_3_loc_channel_dout;

assign feature_Loop_memset_featureHist_proc1_U0_p_read2 = boundingBoxes_2_loc_channel_dout;

assign feature_Loop_memset_featureHist_proc1_U0_p_read3 = boundingBoxes_1_loc_channel_dout;

assign feature_gmem_m_axi_U_ap_dummy_ce = ap_const_logic_1;

assign feature_gmem_offset_m_axi_U_ap_dummy_ce = ap_const_logic_1;

assign featureh_channel_U_ap_dummy_ce = ap_const_logic_1;

assign featureh_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_din;

assign featureh_channel_read = feature_Loop_memcpy_featureh_featureHi_U0_featureh1_read;

assign featureh_channel_write = feature_Loop_memcpy_boundingBoxes_boun_U0_featureh_out_write;

assign frame_in_channel_U_ap_dummy_ce = ap_const_logic_1;

assign frame_in_channel_din = feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_din;

assign frame_in_channel_read = feature_Loop_memset_featureHist_proc1_U0_frame_in1_read;

assign frame_in_channel_write = feature_Loop_memcpy_boundingBoxes_boun_U0_frame_in_out_write;

assign gmem_ARADDR = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARADDR;

assign gmem_ARBURST = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARBURST;

assign gmem_ARCACHE = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARCACHE;

assign gmem_ARID = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARID;

assign gmem_ARLEN = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLEN;

assign gmem_ARLOCK = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARLOCK;

assign gmem_ARPROT = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARPROT;

assign gmem_ARQOS = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARQOS;

assign gmem_ARREGION = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARREGION;

assign gmem_ARSIZE = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARSIZE;

assign gmem_ARUSER = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARUSER;

assign gmem_ARVALID = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_ARVALID;

assign gmem_AWADDR = ap_const_lv32_0;

assign gmem_AWBURST = ap_const_lv2_0;

assign gmem_AWCACHE = ap_const_lv4_0;

assign gmem_AWID = ap_const_lv1_0;

assign gmem_AWLEN = ap_const_lv32_0;

assign gmem_AWLOCK = ap_const_lv2_0;

assign gmem_AWPROT = ap_const_lv3_0;

assign gmem_AWQOS = ap_const_lv4_0;

assign gmem_AWREGION = ap_const_lv4_0;

assign gmem_AWSIZE = ap_const_lv3_0;

assign gmem_AWUSER = ap_const_lv1_0;

assign gmem_AWVALID = ap_const_logic_0;

assign gmem_BREADY = ap_const_logic_0;

assign gmem_RREADY = feature_Loop_memset_featureHist_proc1_U0_m_axi_frame_in_RREADY;

assign gmem_WDATA = ap_const_lv8_0;

assign gmem_WID = ap_const_lv1_0;

assign gmem_WLAST = ap_const_logic_0;

assign gmem_WSTRB = ap_const_lv1_0;

assign gmem_WUSER = ap_const_lv1_0;

assign gmem_WVALID = ap_const_logic_0;

assign gmem_offset_ARADDR = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARADDR;

assign gmem_offset_ARBURST = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARBURST;

assign gmem_offset_ARCACHE = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARCACHE;

assign gmem_offset_ARID = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARID;

assign gmem_offset_ARLEN = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLEN;

assign gmem_offset_ARLOCK = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARLOCK;

assign gmem_offset_ARPROT = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARPROT;

assign gmem_offset_ARQOS = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARQOS;

assign gmem_offset_ARREGION = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARREGION;

assign gmem_offset_ARSIZE = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARSIZE;

assign gmem_offset_ARUSER = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARUSER;

assign gmem_offset_ARVALID = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_ARVALID;

assign gmem_offset_AWADDR = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWADDR;

assign gmem_offset_AWBURST = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWBURST;

assign gmem_offset_AWCACHE = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWCACHE;

assign gmem_offset_AWID = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWID;

assign gmem_offset_AWLEN = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLEN;

assign gmem_offset_AWLOCK = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWLOCK;

assign gmem_offset_AWPROT = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWPROT;

assign gmem_offset_AWQOS = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWQOS;

assign gmem_offset_AWREGION = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWREGION;

assign gmem_offset_AWSIZE = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWSIZE;

assign gmem_offset_AWUSER = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWUSER;

assign gmem_offset_AWVALID = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_AWVALID;

assign gmem_offset_BREADY = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_BREADY;

assign gmem_offset_RREADY = feature_Loop_memcpy_boundingBoxes_boun_U0_m_axi_bounding_RREADY;

assign gmem_offset_WDATA = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WDATA;

assign gmem_offset_WID = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WID;

assign gmem_offset_WLAST = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WLAST;

assign gmem_offset_WSTRB = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WSTRB;

assign gmem_offset_WUSER = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WUSER;

assign gmem_offset_WVALID = feature_Loop_memcpy_featureh_featureHi_U0_m_axi_featureh_WVALID;


endmodule //feature

