// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module feature_Loop_memset_featureHist_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        featureHist_address0,
        featureHist_ce0,
        featureHist_we0,
        featureHist_d0,
        featureHist_q0,
        featureHist_address1,
        featureHist_ce1,
        featureHist_we1,
        featureHist_d1,
        featureHist_q1,
        m_axi_frame_in_AWVALID,
        m_axi_frame_in_AWREADY,
        m_axi_frame_in_AWADDR,
        m_axi_frame_in_AWID,
        m_axi_frame_in_AWLEN,
        m_axi_frame_in_AWSIZE,
        m_axi_frame_in_AWBURST,
        m_axi_frame_in_AWLOCK,
        m_axi_frame_in_AWCACHE,
        m_axi_frame_in_AWPROT,
        m_axi_frame_in_AWQOS,
        m_axi_frame_in_AWREGION,
        m_axi_frame_in_AWUSER,
        m_axi_frame_in_WVALID,
        m_axi_frame_in_WREADY,
        m_axi_frame_in_WDATA,
        m_axi_frame_in_WSTRB,
        m_axi_frame_in_WLAST,
        m_axi_frame_in_WID,
        m_axi_frame_in_WUSER,
        m_axi_frame_in_ARVALID,
        m_axi_frame_in_ARREADY,
        m_axi_frame_in_ARADDR,
        m_axi_frame_in_ARID,
        m_axi_frame_in_ARLEN,
        m_axi_frame_in_ARSIZE,
        m_axi_frame_in_ARBURST,
        m_axi_frame_in_ARLOCK,
        m_axi_frame_in_ARCACHE,
        m_axi_frame_in_ARPROT,
        m_axi_frame_in_ARQOS,
        m_axi_frame_in_ARREGION,
        m_axi_frame_in_ARUSER,
        m_axi_frame_in_RVALID,
        m_axi_frame_in_RREADY,
        m_axi_frame_in_RDATA,
        m_axi_frame_in_RLAST,
        m_axi_frame_in_RID,
        m_axi_frame_in_RUSER,
        m_axi_frame_in_RRESP,
        m_axi_frame_in_BVALID,
        m_axi_frame_in_BREADY,
        m_axi_frame_in_BRESP,
        m_axi_frame_in_BID,
        m_axi_frame_in_BUSER,
        frame_in1_dout,
        frame_in1_empty_n,
        frame_in1_read,
        p_read,
        p_read1,
        p_read2,
        p_read3
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 25'b1;
parameter    ap_ST_st2_fsm_1 = 25'b10;
parameter    ap_ST_st3_fsm_2 = 25'b100;
parameter    ap_ST_st4_fsm_3 = 25'b1000;
parameter    ap_ST_st5_fsm_4 = 25'b10000;
parameter    ap_ST_st6_fsm_5 = 25'b100000;
parameter    ap_ST_st7_fsm_6 = 25'b1000000;
parameter    ap_ST_st8_fsm_7 = 25'b10000000;
parameter    ap_ST_st9_fsm_8 = 25'b100000000;
parameter    ap_ST_st10_fsm_9 = 25'b1000000000;
parameter    ap_ST_pp0_stg0_fsm_10 = 25'b10000000000;
parameter    ap_ST_st14_fsm_11 = 25'b100000000000;
parameter    ap_ST_st15_fsm_12 = 25'b1000000000000;
parameter    ap_ST_pp1_stg0_fsm_13 = 25'b10000000000000;
parameter    ap_ST_pp1_stg1_fsm_14 = 25'b100000000000000;
parameter    ap_ST_pp1_stg2_fsm_15 = 25'b1000000000000000;
parameter    ap_ST_pp1_stg3_fsm_16 = 25'b10000000000000000;
parameter    ap_ST_pp1_stg4_fsm_17 = 25'b100000000000000000;
parameter    ap_ST_pp1_stg5_fsm_18 = 25'b1000000000000000000;
parameter    ap_ST_pp1_stg6_fsm_19 = 25'b10000000000000000000;
parameter    ap_ST_pp1_stg7_fsm_20 = 25'b100000000000000000000;
parameter    ap_ST_pp1_stg8_fsm_21 = 25'b1000000000000000000000;
parameter    ap_ST_pp1_stg9_fsm_22 = 25'b10000000000000000000000;
parameter    ap_ST_pp1_stg10_fsm_23 = 25'b100000000000000000000000;
parameter    ap_ST_pp1_stg11_fsm_24 = 25'b1000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_780 = 32'b11110000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv9_1FF = 9'b111111111;
parameter    ap_const_lv7_78 = 7'b1111000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv33_0 = 33'b000000000000000000000000000000000;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv7_50 = 7'b1010000;
parameter    ap_const_lv11_3C0 = 11'b1111000000;
parameter    ap_const_lv9_140 = 9'b101000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv11_18 = 11'b11000;
parameter    ap_const_lv9_8 = 9'b1000;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv9_2 = 9'b10;
parameter    ap_const_lv9_3 = 9'b11;
parameter    ap_const_lv9_4 = 9'b100;
parameter    ap_const_lv9_5 = 9'b101;
parameter    ap_const_lv9_6 = 9'b110;
parameter    ap_const_lv9_7 = 9'b111;
parameter    ap_const_lv11_5 = 11'b101;
parameter    ap_const_lv11_3 = 11'b11;
parameter    ap_const_lv11_4 = 11'b100;
parameter    ap_const_lv11_8 = 11'b1000;
parameter    ap_const_lv11_7 = 11'b111;
parameter    ap_const_lv11_6 = 11'b110;
parameter    ap_const_lv11_B = 11'b1011;
parameter    ap_const_lv11_9 = 11'b1001;
parameter    ap_const_lv11_A = 11'b1010;
parameter    ap_const_lv11_E = 11'b1110;
parameter    ap_const_lv11_D = 11'b1101;
parameter    ap_const_lv11_C = 11'b1100;
parameter    ap_const_lv11_11 = 11'b10001;
parameter    ap_const_lv11_F = 11'b1111;
parameter    ap_const_lv11_10 = 11'b10000;
parameter    ap_const_lv11_14 = 11'b10100;
parameter    ap_const_lv11_13 = 11'b10011;
parameter    ap_const_lv11_12 = 11'b10010;
parameter    ap_const_lv11_17 = 11'b10111;
parameter    ap_const_lv11_15 = 11'b10101;
parameter    ap_const_lv11_16 = 11'b10110;
parameter    ap_const_lv34_11112 = 34'b10001000100010010;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [8:0] featureHist_address0;
output   featureHist_ce0;
output   featureHist_we0;
output  [15:0] featureHist_d0;
input  [15:0] featureHist_q0;
output  [8:0] featureHist_address1;
output   featureHist_ce1;
output   featureHist_we1;
output  [15:0] featureHist_d1;
input  [15:0] featureHist_q1;
output   m_axi_frame_in_AWVALID;
input   m_axi_frame_in_AWREADY;
output  [31:0] m_axi_frame_in_AWADDR;
output  [0:0] m_axi_frame_in_AWID;
output  [31:0] m_axi_frame_in_AWLEN;
output  [2:0] m_axi_frame_in_AWSIZE;
output  [1:0] m_axi_frame_in_AWBURST;
output  [1:0] m_axi_frame_in_AWLOCK;
output  [3:0] m_axi_frame_in_AWCACHE;
output  [2:0] m_axi_frame_in_AWPROT;
output  [3:0] m_axi_frame_in_AWQOS;
output  [3:0] m_axi_frame_in_AWREGION;
output  [0:0] m_axi_frame_in_AWUSER;
output   m_axi_frame_in_WVALID;
input   m_axi_frame_in_WREADY;
output  [7:0] m_axi_frame_in_WDATA;
output  [0:0] m_axi_frame_in_WSTRB;
output   m_axi_frame_in_WLAST;
output  [0:0] m_axi_frame_in_WID;
output  [0:0] m_axi_frame_in_WUSER;
output   m_axi_frame_in_ARVALID;
input   m_axi_frame_in_ARREADY;
output  [31:0] m_axi_frame_in_ARADDR;
output  [0:0] m_axi_frame_in_ARID;
output  [31:0] m_axi_frame_in_ARLEN;
output  [2:0] m_axi_frame_in_ARSIZE;
output  [1:0] m_axi_frame_in_ARBURST;
output  [1:0] m_axi_frame_in_ARLOCK;
output  [3:0] m_axi_frame_in_ARCACHE;
output  [2:0] m_axi_frame_in_ARPROT;
output  [3:0] m_axi_frame_in_ARQOS;
output  [3:0] m_axi_frame_in_ARREGION;
output  [0:0] m_axi_frame_in_ARUSER;
input   m_axi_frame_in_RVALID;
output   m_axi_frame_in_RREADY;
input  [7:0] m_axi_frame_in_RDATA;
input   m_axi_frame_in_RLAST;
input  [0:0] m_axi_frame_in_RID;
input  [0:0] m_axi_frame_in_RUSER;
input  [1:0] m_axi_frame_in_RRESP;
input   m_axi_frame_in_BVALID;
output   m_axi_frame_in_BREADY;
input  [1:0] m_axi_frame_in_BRESP;
input  [0:0] m_axi_frame_in_BID;
input  [0:0] m_axi_frame_in_BUSER;
input  [31:0] frame_in1_dout;
input   frame_in1_empty_n;
output   frame_in1_read;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] featureHist_address0;
reg featureHist_ce0;
reg featureHist_we0;
reg[15:0] featureHist_d0;
reg[8:0] featureHist_address1;
reg featureHist_ce1;
reg featureHist_we1;
reg[15:0] featureHist_d1;
reg m_axi_frame_in_ARVALID;
reg m_axi_frame_in_RREADY;
reg frame_in1_read;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm = 25'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_44;
reg   [10:0] indvar2_i_reg_549;
reg   [10:0] ap_reg_ppstg_indvar2_i_reg_549_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_10;
reg    ap_sig_bdd_136;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] exitcond5_i_reg_1722;
reg    ap_sig_bdd_144;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [6:0] indvar_flatten_i_reg_561;
reg   [10:0] iterator_i_reg_572;
reg   [1:0] i_i_reg_583;
reg   [10:0] iterator_i_46_reg_594;
reg   [8:0] j_i_reg_605;
wire   [2:0] grp_fu_616_p4;
reg   [2:0] reg_652;
reg    ap_sig_cseq_ST_pp1_stg2_fsm_15;
reg    ap_sig_bdd_169;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
reg   [0:0] exitcond_flatten_i_reg_1757;
reg   [0:0] or_cond1_i_reg_1850;
reg   [0:0] or_cond_i_reg_1854;
reg    ap_sig_cseq_ST_pp1_stg4_fsm_17;
reg    ap_sig_bdd_190;
reg   [0:0] or_cond3_i_reg_1868;
reg   [0:0] or_cond2_i_reg_1872;
reg    ap_sig_cseq_ST_pp1_stg5_fsm_18;
reg    ap_sig_bdd_206;
reg   [0:0] or_cond5_i_reg_1876;
reg   [0:0] or_cond4_i_reg_1880;
reg    ap_sig_cseq_ST_pp1_stg7_fsm_20;
reg    ap_sig_bdd_222;
reg   [0:0] or_cond7_i_reg_1884;
reg   [0:0] or_cond6_i_reg_1888;
reg    ap_sig_cseq_ST_pp1_stg9_fsm_22;
reg    ap_sig_bdd_238;
reg   [0:0] or_cond9_i_reg_1892;
reg   [0:0] or_cond8_i_reg_1896;
reg   [2:0] reg_656;
reg    ap_sig_cseq_ST_pp1_stg3_fsm_16;
reg    ap_sig_bdd_256;
reg   [0:0] or_cond11_i_reg_1900;
reg   [0:0] or_cond10_i_reg_1904;
reg   [2:0] reg_660;
reg    ap_sig_cseq_ST_pp1_stg6_fsm_19;
reg    ap_sig_bdd_277;
reg    ap_sig_cseq_ST_pp1_stg10_fsm_23;
reg    ap_sig_bdd_287;
reg   [2:0] reg_664;
reg    ap_sig_cseq_ST_pp1_stg8_fsm_21;
reg    ap_sig_bdd_299;
reg    ap_sig_cseq_ST_pp1_stg11_fsm_24;
reg    ap_sig_bdd_309;
reg   [0:0] or_cond13_i_reg_1908;
reg   [0:0] or_cond12_i_reg_1912;
reg   [2:0] reg_668;
reg   [2:0] reg_672;
reg    ap_sig_cseq_ST_pp1_stg1_fsm_14;
reg    ap_sig_bdd_328;
reg   [0:0] or_cond15_i_reg_1916;
reg   [0:0] or_cond14_i_reg_1920;
reg    ap_sig_bdd_345;
wire  signed [33:0] tmp_cast_i_fu_676_p1;
reg  signed [33:0] tmp_cast_i_reg_1685;
wire   [8:0] indvarinc_i_fu_685_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_363;
wire   [16:0] tmp_91_cast_i_fu_697_p1;
reg   [16:0] tmp_91_cast_i_reg_1698;
wire   [0:0] tmp_2_i_fu_691_p2;
wire   [16:0] tmp_13_7_cast_i_fu_700_p1;
reg   [16:0] tmp_13_7_cast_i_reg_1703;
wire   [6:0] k_fu_709_p2;
reg   [6:0] k_reg_1711;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_380;
reg   [31:0] frame_in_addr_reg_1716;
wire   [0:0] exitcond3_i_fu_703_p2;
wire   [0:0] exitcond5_i_fu_768_p2;
reg   [0:0] ap_reg_ppstg_exitcond5_i_reg_1722_pp0_it1;
wire   [10:0] indvar_next2_i_fu_774_p2;
reg   [10:0] indvar_next2_i_reg_1726;
reg   [7:0] frame_in_addr_read_reg_1731;
wire   [32:0] tmp_4_fu_819_p1;
reg   [32:0] tmp_4_reg_1736;
reg    ap_sig_cseq_ST_st14_fsm_11;
reg    ap_sig_bdd_404;
reg   [0:0] tmp_5_reg_1741;
reg   [10:0] tmp_7_reg_1747;
wire   [8:0] tmp_32_i_fu_882_p3;
reg   [8:0] tmp_32_i_reg_1752;
reg    ap_sig_cseq_ST_st15_fsm_12;
reg    ap_sig_bdd_417;
wire   [0:0] exitcond_flatten_i_fu_889_p2;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_13;
reg    ap_sig_bdd_425;
wire   [6:0] indvar_flatten_next_i_fu_895_p2;
reg   [6:0] indvar_flatten_next_i_reg_1761;
wire   [10:0] iterator_mid2_i_fu_913_p3;
reg   [10:0] iterator_mid2_i_reg_1766;
wire   [8:0] j_mid2_i_fu_921_p3;
reg   [8:0] j_mid2_i_reg_1794;
wire   [10:0] iterator_mid2_i_44_fu_929_p3;
reg   [10:0] iterator_mid2_i_44_reg_1806;
wire   [1:0] i_mid2_i_fu_943_p3;
reg   [1:0] i_mid2_i_reg_1811;
wire   [0:0] tmp_4_i_fu_964_p2;
reg   [0:0] tmp_4_i_reg_1816;
wire   [0:0] tmp_14_7_i_fu_969_p2;
reg   [0:0] tmp_14_7_i_reg_1828;
wire   [10:0] tmp_34_7_i_fu_974_p2;
reg   [10:0] tmp_34_7_i_reg_1840;
wire   [8:0] j_1_7_i_fu_980_p2;
reg   [8:0] j_1_7_i_reg_1845;
wire   [0:0] or_cond1_i_fu_994_p2;
wire   [0:0] or_cond_i_fu_1004_p2;
wire   [0:0] or_cond3_i_fu_1043_p2;
wire   [0:0] or_cond2_i_fu_1053_p2;
wire   [0:0] or_cond5_i_fu_1072_p2;
wire   [0:0] or_cond4_i_fu_1082_p2;
wire   [0:0] or_cond7_i_fu_1101_p2;
wire   [0:0] or_cond6_i_fu_1111_p2;
wire   [0:0] or_cond9_i_fu_1130_p2;
wire   [0:0] or_cond8_i_fu_1140_p2;
wire   [0:0] or_cond11_i_fu_1159_p2;
reg   [0:0] ap_reg_ppstg_or_cond11_i_reg_1900_pp1_it1;
wire   [0:0] or_cond10_i_fu_1169_p2;
reg   [0:0] ap_reg_ppstg_or_cond10_i_reg_1904_pp1_it1;
wire   [0:0] or_cond13_i_fu_1188_p2;
reg   [0:0] ap_reg_ppstg_or_cond13_i_reg_1908_pp1_it1;
wire   [0:0] or_cond12_i_fu_1198_p2;
reg   [0:0] ap_reg_ppstg_or_cond12_i_reg_1912_pp1_it1;
wire   [0:0] or_cond15_i_fu_1217_p2;
reg   [0:0] ap_reg_ppstg_or_cond15_i_reg_1916_pp1_it1;
wire   [0:0] or_cond14_i_fu_1227_p2;
reg   [0:0] ap_reg_ppstg_or_cond14_i_reg_1920_pp1_it1;
reg   [8:0] featureHist_addr_1_reg_1934;
reg   [8:0] featureHist_addr_2_reg_1960;
reg   [8:0] featureHist_addr_3_reg_1985;
reg   [8:0] featureHist_addr_4_reg_2010;
reg   [8:0] featureHist_addr_5_reg_2035;
reg   [2:0] tmp_29_6_i_reg_2050;
reg   [2:0] tmp_47_i_reg_2055;
reg   [8:0] featureHist_addr_6_reg_2070;
reg   [2:0] tmp_29_7_i_reg_2075;
reg   [8:0] featureHist_addr_7_reg_2080;
reg   [8:0] featureHist_addr_8_reg_2086;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_615;
reg   [10:0] rgb_i_address0;
reg    rgb_i_ce0;
wire   [7:0] rgb_i_q0;
reg   [10:0] rgb_i_address1;
reg    rgb_i_ce1;
reg    rgb_i_we1;
wire   [7:0] rgb_i_d1;
wire   [7:0] rgb_i_q1;
reg   [8:0] invdar_i_reg_526;
reg   [6:0] k_i_reg_537;
reg   [10:0] indvar2_i_phi_fu_553_p4;
reg   [6:0] indvar_flatten_i_phi_fu_565_p4;
reg   [10:0] iterator_i_phi_fu_576_p4;
reg   [1:0] i_i_phi_fu_587_p4;
reg   [10:0] iterator_i_46_phi_fu_598_p4;
reg   [8:0] j_i_phi_fu_609_p4;
wire   [63:0] tmp_1_i_fu_680_p1;
wire   [63:0] tmp_8_i_fu_780_p1;
wire   [63:0] tmp_12_i_fu_1014_p1;
wire   [63:0] tmp_15_i_fu_1024_p1;
wire   [63:0] tmp_20_i_fu_1232_p1;
wire   [63:0] tmp_18_1_i_fu_1241_p1;
wire   [63:0] tmp_23_i_fu_1266_p1;
wire   [63:0] tmp_23_1_i_fu_1281_p1;
wire   [63:0] tmp_27_1_i_fu_1286_p1;
wire   [63:0] tmp_18_2_i_fu_1296_p1;
wire   [63:0] tmp_23_2_i_fu_1306_p1;
wire   [63:0] tmp_32_1_i_fu_1331_p1;
wire   [63:0] tmp_27_2_i_fu_1341_p1;
wire   [63:0] tmp_18_3_i_fu_1351_p1;
wire   [63:0] tmp_23_3_i_fu_1366_p1;
wire   [63:0] tmp_27_3_i_fu_1371_p1;
wire   [63:0] tmp_32_2_i_fu_1396_p1;
wire   [63:0] tmp_18_4_i_fu_1406_p1;
wire   [63:0] tmp_23_4_i_fu_1416_p1;
wire   [63:0] tmp_27_4_i_fu_1426_p1;
wire   [63:0] tmp_18_5_i_fu_1436_p1;
wire   [63:0] tmp_32_3_i_fu_1461_p1;
wire   [63:0] tmp_23_5_i_fu_1476_p1;
wire   [63:0] tmp_27_5_i_fu_1481_p1;
wire   [63:0] tmp_18_6_i_fu_1491_p1;
wire   [63:0] tmp_23_6_i_fu_1501_p1;
wire   [63:0] tmp_32_4_i_fu_1526_p1;
wire   [63:0] tmp_27_6_i_fu_1536_p1;
wire   [63:0] tmp_18_7_i_fu_1546_p1;
wire   [63:0] tmp_23_7_i_fu_1561_p1;
wire   [63:0] tmp_27_7_i_fu_1566_p1;
wire   [63:0] tmp_32_5_i_fu_1591_p1;
wire   [63:0] tmp_32_6_i_fu_1615_p1;
wire   [63:0] tmp_32_7_i_fu_1638_p1;
wire  signed [63:0] tmp_3_fu_758_p1;
reg    ap_reg_ioackin_m_axi_frame_in_ARREADY = 1'b0;
reg    ap_sig_ioackin_m_axi_frame_in_ARREADY;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_727;
wire   [15:0] grp_fu_636_p2;
wire   [15:0] grp_fu_644_p2;
wire   [17:0] p_shl_i_fu_715_p3;
wire   [13:0] p_shl1_i_fu_727_p3;
wire   [18:0] p_shl_cast_i_fu_723_p1;
wire   [18:0] p_shl1_cast_i_fu_735_p1;
wire   [18:0] tmp_3_i_fu_739_p2;
wire  signed [31:0] tmp_fu_745_p1;
wire   [33:0] tmp_1_fu_749_p1;
wire   [33:0] tmp_2_fu_753_p2;
wire   [14:0] p_shl2_i_fu_785_p3;
wire   [10:0] p_shl3_i_fu_797_p3;
wire   [15:0] p_shl2_cast_i_fu_793_p1;
wire   [15:0] p_shl3_cast_i_fu_805_p1;
wire  signed [15:0] tmp_5_i_fu_809_p2;
wire  signed [33:0] mul_i_fu_1643_p2;
wire   [32:0] neg_mul_i_fu_839_p2;
wire   [9:0] tmp_6_fu_844_p4;
wire  signed [16:0] tmp_13_i_fu_854_p1;
wire  signed [16:0] tmp_14_i_fu_858_p1;
wire   [16:0] p_v_i_fu_861_p3;
wire   [8:0] tmp_8_fu_868_p1;
wire   [8:0] neg_ti_i_fu_872_p2;
wire   [8:0] tmp_9_fu_878_p1;
wire   [0:0] exitcond1215_i_fu_907_p2;
wire   [10:0] iterator_1_dup_i_fu_901_p2;
wire   [1:0] i_1211_i_fu_937_p2;
wire   [8:0] i_cast_i_fu_951_p1;
wire   [8:0] tmp_i_fu_955_p2;
wire  signed [16:0] tmp_cast_i_45_fu_960_p1;
wire   [15:0] j_cast_cast_i_fu_986_p1;
wire   [0:0] tmp_6_i_fu_989_p2;
wire   [0:0] tmp_10_i_fu_999_p2;
wire   [10:0] tmp_17_i_fu_1009_p2;
wire   [10:0] tmp_22_i_fu_1019_p2;
wire   [8:0] j_1_i_fu_1029_p2;
wire   [15:0] j_1_cast_cast_i_fu_1034_p1;
wire   [0:0] tmp_12_1_i_fu_1038_p2;
wire   [0:0] tmp_16_1_i_fu_1048_p2;
wire   [8:0] j_1_1_i_fu_1058_p2;
wire   [15:0] j_1_1_cast_cast_i_fu_1063_p1;
wire   [0:0] tmp_12_2_i_fu_1067_p2;
wire   [0:0] tmp_16_2_i_fu_1077_p2;
wire   [8:0] j_1_2_i_fu_1087_p2;
wire   [15:0] j_1_2_cast_cast_i_fu_1092_p1;
wire   [0:0] tmp_12_3_i_fu_1096_p2;
wire   [0:0] tmp_16_3_i_fu_1106_p2;
wire   [8:0] j_1_3_i_fu_1116_p2;
wire   [15:0] j_1_3_cast_cast_i_fu_1121_p1;
wire   [0:0] tmp_12_4_i_fu_1125_p2;
wire   [0:0] tmp_16_4_i_fu_1135_p2;
wire   [8:0] j_1_4_i_fu_1145_p2;
wire   [15:0] j_1_4_cast_cast_i_fu_1150_p1;
wire   [0:0] tmp_12_5_i_fu_1154_p2;
wire   [0:0] tmp_16_5_i_fu_1164_p2;
wire   [8:0] j_1_5_i_fu_1174_p2;
wire   [15:0] j_1_5_cast_cast_i_fu_1179_p1;
wire   [0:0] tmp_12_6_i_fu_1183_p2;
wire   [0:0] tmp_16_6_i_fu_1193_p2;
wire   [8:0] j_1_6_i_fu_1203_p2;
wire   [15:0] j_1_6_cast_cast_i_fu_1208_p1;
wire   [0:0] tmp_12_7_i_fu_1212_p2;
wire   [0:0] tmp_16_7_i_fu_1222_p2;
wire   [10:0] tmp_17_1_i_fu_1236_p2;
wire   [8:0] tmp_19_i_fu_1246_p4;
wire   [8:0] tmp_29_cast_i_fu_1256_p1;
wire   [8:0] tmp_22_i_49_fu_1260_p2;
wire   [10:0] tmp_22_1_i_fu_1276_p2;
wire   [10:0] tmp_34_i_fu_1271_p2;
wire   [10:0] tmp_17_2_i_fu_1291_p2;
wire   [10:0] tmp_22_2_i_fu_1301_p2;
wire   [8:0] tmp_30_1_i_fu_1311_p4;
wire   [8:0] tmp_29_1_cast_i_fu_1321_p1;
wire   [8:0] tmp_31_1_i_fu_1325_p2;
wire   [10:0] tmp_34_1_i_fu_1336_p2;
wire   [10:0] tmp_17_3_i_fu_1346_p2;
wire   [10:0] tmp_22_3_i_fu_1361_p2;
wire   [10:0] tmp_34_2_i_fu_1356_p2;
wire   [8:0] tmp_30_2_i_fu_1376_p4;
wire   [8:0] tmp_29_2_cast_i_fu_1386_p1;
wire   [8:0] tmp_31_2_i_fu_1390_p2;
wire   [10:0] tmp_17_4_i_fu_1401_p2;
wire   [10:0] tmp_22_4_i_fu_1411_p2;
wire   [10:0] tmp_34_3_i_fu_1421_p2;
wire   [10:0] tmp_17_5_i_fu_1431_p2;
wire   [8:0] tmp_30_3_i_fu_1441_p4;
wire   [8:0] tmp_29_3_cast_i_fu_1451_p1;
wire   [8:0] tmp_31_3_i_fu_1455_p2;
wire   [10:0] tmp_22_5_i_fu_1471_p2;
wire   [10:0] tmp_34_4_i_fu_1466_p2;
wire   [10:0] tmp_17_6_i_fu_1486_p2;
wire   [10:0] tmp_22_6_i_fu_1496_p2;
wire   [8:0] tmp_30_4_i_fu_1506_p4;
wire   [8:0] tmp_29_4_cast_i_fu_1516_p1;
wire   [8:0] tmp_31_4_i_fu_1520_p2;
wire   [10:0] tmp_34_5_i_fu_1531_p2;
wire   [10:0] tmp_17_7_i_fu_1541_p2;
wire   [10:0] tmp_22_7_i_fu_1556_p2;
wire   [10:0] tmp_34_6_i_fu_1551_p2;
wire   [8:0] tmp_30_5_i_fu_1571_p4;
wire   [8:0] tmp_29_5_cast_i_fu_1581_p1;
wire   [8:0] tmp_31_5_i_fu_1585_p2;
wire   [8:0] tmp_30_6_i_fu_1596_p4;
wire   [8:0] tmp_29_6_cast_i_fu_1606_p1;
wire   [8:0] tmp_31_6_i_fu_1609_p2;
wire   [8:0] tmp_30_7_i_fu_1620_p4;
wire   [8:0] tmp_29_7_cast_i_fu_1629_p1;
wire   [8:0] tmp_31_7_i_fu_1632_p2;
wire   [17:0] mul_i_fu_1643_p0;
reg   [24:0] ap_NS_fsm;


feature_Loop_memset_featureHist_proc1_rgb_i #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
rgb_i_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( rgb_i_address0 ),
    .ce0( rgb_i_ce0 ),
    .q0( rgb_i_q0 ),
    .address1( rgb_i_address1 ),
    .ce1( rgb_i_ce1 ),
    .we1( rgb_i_we1 ),
    .d1( rgb_i_d1 ),
    .q1( rgb_i_q1 )
);

feature_mul_mul_18ns_16s_34_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 34 ))
feature_mul_mul_18ns_16s_34_1_U7(
    .din0( mul_i_fu_1643_p0 ),
    .din1( tmp_5_i_fu_809_p2 ),
    .dout( mul_i_fu_1643_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond3_i_fu_703_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_m_axi_frame_in_ARREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_frame_in_ARREADY <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_m_axi_frame_in_ARREADY)) begin
                ap_reg_ioackin_m_axi_frame_in_ARREADY <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == m_axi_frame_in_ARREADY)) begin
                ap_reg_ioackin_m_axi_frame_in_ARREADY <= ap_const_logic_1;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond5_i_fu_768_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond5_i_fu_768_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond5_i_fu_768_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13) & ~(ap_const_lv1_0 == exitcond_flatten_i_fu_889_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24) & ~(ap_const_lv1_0 == exitcond_flatten_i_reg_1757)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        i_i_reg_583 <= i_mid2_i_reg_1811;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        i_i_reg_583 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & (ap_const_lv1_0 == exitcond5_i_reg_1722) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        indvar2_i_reg_549 <= indvar_next2_i_reg_1726;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        indvar2_i_reg_549 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        indvar_flatten_i_reg_561 <= indvar_flatten_next_i_reg_1761;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        indvar_flatten_i_reg_561 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_345)) begin
        invdar_i_reg_526 <= ap_const_lv9_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == tmp_2_i_fu_691_p2))) begin
        invdar_i_reg_526 <= indvarinc_i_fu_685_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        iterator_i_46_reg_594 <= tmp_34_7_i_reg_1840;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        iterator_i_46_reg_594 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        iterator_i_reg_572 <= iterator_mid2_i_44_reg_1806;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        iterator_i_reg_572 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        j_i_reg_605 <= j_1_7_i_reg_1845;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        j_i_reg_605 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13) & ~(ap_const_lv1_0 == exitcond_flatten_i_fu_889_p2))) begin
        k_i_reg_537 <= k_reg_1711;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_2_i_fu_691_p2))) begin
        k_i_reg_537 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ap_reg_ppstg_exitcond5_i_reg_1722_pp0_it1 <= exitcond5_i_reg_1722;
        ap_reg_ppstg_indvar2_i_reg_549_pp0_it1 <= indvar2_i_reg_549;
        exitcond5_i_reg_1722 <= exitcond5_i_fu_768_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14)) begin
        ap_reg_ppstg_or_cond10_i_reg_1904_pp1_it1 <= or_cond10_i_reg_1904;
        ap_reg_ppstg_or_cond11_i_reg_1900_pp1_it1 <= or_cond11_i_reg_1900;
        ap_reg_ppstg_or_cond12_i_reg_1912_pp1_it1 <= or_cond12_i_reg_1912;
        ap_reg_ppstg_or_cond13_i_reg_1908_pp1_it1 <= or_cond13_i_reg_1908;
        ap_reg_ppstg_or_cond14_i_reg_1920_pp1_it1 <= or_cond14_i_reg_1920;
        ap_reg_ppstg_or_cond15_i_reg_1916_pp1_it1 <= or_cond15_i_reg_1916;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) begin
        exitcond_flatten_i_reg_1757 <= exitcond_flatten_i_fu_889_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond1_i_reg_1850) & (ap_const_lv1_0 == or_cond_i_reg_1854) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16))) begin
        featureHist_addr_1_reg_1934 <= tmp_23_i_fu_1266_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond3_i_reg_1868) & (ap_const_lv1_0 == or_cond2_i_reg_1872) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18))) begin
        featureHist_addr_2_reg_1960 <= tmp_32_1_i_fu_1331_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond5_i_reg_1876) & (ap_const_lv1_0 == or_cond4_i_reg_1880) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20))) begin
        featureHist_addr_3_reg_1985 <= tmp_32_2_i_fu_1396_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond7_i_reg_1884) & (ap_const_lv1_0 == or_cond6_i_reg_1888) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22))) begin
        featureHist_addr_4_reg_2010 <= tmp_32_3_i_fu_1461_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond9_i_reg_1892) & (ap_const_lv1_0 == or_cond8_i_reg_1896) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24))) begin
        featureHist_addr_5_reg_2035 <= tmp_32_4_i_fu_1526_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == or_cond11_i_reg_1900) & (ap_const_lv1_0 == or_cond10_i_reg_1904) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14))) begin
        featureHist_addr_6_reg_2070 <= tmp_32_5_i_fu_1591_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond13_i_reg_1908_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond12_i_reg_1912_pp1_it1))) begin
        featureHist_addr_7_reg_2080 <= tmp_32_6_i_fu_1615_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond15_i_reg_1916_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond14_i_reg_1920_pp1_it1))) begin
        featureHist_addr_8_reg_2086 <= tmp_32_7_i_fu_1638_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & (ap_const_lv1_0 == exitcond5_i_reg_1722) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        frame_in_addr_read_reg_1731 <= m_axi_frame_in_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond3_i_fu_703_p2))) begin
        frame_in_addr_reg_1716 <= tmp_3_fu_758_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13) & (ap_const_lv1_0 == exitcond_flatten_i_fu_889_p2))) begin
        i_mid2_i_reg_1811 <= i_mid2_i_fu_943_p3;
        iterator_mid2_i_44_reg_1806 <= iterator_mid2_i_44_fu_929_p3;
        j_1_7_i_reg_1845 <= j_1_7_i_fu_980_p2;
        tmp_34_7_i_reg_1840 <= tmp_34_7_i_fu_974_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        indvar_flatten_next_i_reg_1761 <= indvar_flatten_next_i_fu_895_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        indvar_next2_i_reg_1726 <= indvar_next2_i_fu_774_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13) & (ap_const_lv1_0 == exitcond_flatten_i_fu_889_p2))) begin
        iterator_mid2_i_reg_1766 <= iterator_mid2_i_fu_913_p3;
        j_mid2_i_reg_1794 <= j_mid2_i_fu_921_p3;
        tmp_14_7_i_reg_1828 <= tmp_14_7_i_fu_969_p2;
        tmp_4_i_reg_1816 <= tmp_4_i_fu_964_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        k_reg_1711 <= k_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond11_i_fu_1159_p2))) begin
        or_cond10_i_reg_1904 <= or_cond10_i_fu_1169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14))) begin
        or_cond11_i_reg_1900 <= or_cond11_i_fu_1159_p2;
        or_cond13_i_reg_1908 <= or_cond13_i_fu_1188_p2;
        or_cond15_i_reg_1916 <= or_cond15_i_fu_1217_p2;
        or_cond1_i_reg_1850 <= or_cond1_i_fu_994_p2;
        or_cond3_i_reg_1868 <= or_cond3_i_fu_1043_p2;
        or_cond5_i_reg_1876 <= or_cond5_i_fu_1072_p2;
        or_cond7_i_reg_1884 <= or_cond7_i_fu_1101_p2;
        or_cond9_i_reg_1892 <= or_cond9_i_fu_1130_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond13_i_fu_1188_p2))) begin
        or_cond12_i_reg_1912 <= or_cond12_i_fu_1198_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond15_i_fu_1217_p2))) begin
        or_cond14_i_reg_1920 <= or_cond14_i_fu_1227_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond3_i_fu_1043_p2))) begin
        or_cond2_i_reg_1872 <= or_cond2_i_fu_1053_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond5_i_fu_1072_p2))) begin
        or_cond4_i_reg_1880 <= or_cond4_i_fu_1082_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond7_i_fu_1101_p2))) begin
        or_cond6_i_reg_1888 <= or_cond6_i_fu_1111_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond9_i_fu_1130_p2))) begin
        or_cond8_i_reg_1896 <= or_cond8_i_fu_1140_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond1_i_fu_994_p2))) begin
        or_cond_i_reg_1854 <= or_cond_i_fu_1004_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond1_i_reg_1850) & (ap_const_lv1_0 == or_cond_i_reg_1854)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17) & (ap_const_lv1_0 == or_cond3_i_reg_1868) & (ap_const_lv1_0 == or_cond2_i_reg_1872)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18) & (ap_const_lv1_0 == or_cond5_i_reg_1876) & (ap_const_lv1_0 == or_cond4_i_reg_1880)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20) & (ap_const_lv1_0 == or_cond7_i_reg_1884) & (ap_const_lv1_0 == or_cond6_i_reg_1888)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22) & (ap_const_lv1_0 == or_cond9_i_reg_1892) & (ap_const_lv1_0 == or_cond8_i_reg_1896)))) begin
        reg_652 <= {{rgb_i_q0[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond1_i_reg_1850) & (ap_const_lv1_0 == or_cond_i_reg_1854)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18) & (ap_const_lv1_0 == or_cond5_i_reg_1876) & (ap_const_lv1_0 == or_cond4_i_reg_1880)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20) & (ap_const_lv1_0 == or_cond7_i_reg_1884) & (ap_const_lv1_0 == or_cond6_i_reg_1888)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond3_i_reg_1868) & (ap_const_lv1_0 == or_cond2_i_reg_1872) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22) & (ap_const_lv1_0 == or_cond11_i_reg_1900) & (ap_const_lv1_0 == or_cond10_i_reg_1904)))) begin
        reg_656 <= {{rgb_i_q1[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17) & (ap_const_lv1_0 == or_cond3_i_reg_1868) & (ap_const_lv1_0 == or_cond2_i_reg_1872)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond7_i_reg_1884) & (ap_const_lv1_0 == or_cond6_i_reg_1888) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond11_i_reg_1900) & (ap_const_lv1_0 == or_cond10_i_reg_1904) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)))) begin
        reg_660 <= {{rgb_i_q1[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond5_i_reg_1876) & (ap_const_lv1_0 == or_cond4_i_reg_1880) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond9_i_reg_1892) & (ap_const_lv1_0 == or_cond8_i_reg_1896) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24) & (ap_const_lv1_0 == or_cond13_i_reg_1908) & (ap_const_lv1_0 == or_cond12_i_reg_1912)))) begin
        reg_664 <= {{rgb_i_q0[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond9_i_reg_1892) & (ap_const_lv1_0 == or_cond8_i_reg_1896) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24) & (ap_const_lv1_0 == or_cond13_i_reg_1908) & (ap_const_lv1_0 == or_cond12_i_reg_1912)))) begin
        reg_668 <= {{rgb_i_q1[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond11_i_reg_1900) & (ap_const_lv1_0 == or_cond10_i_reg_1904) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond15_i_reg_1916) & (ap_const_lv1_0 == or_cond14_i_reg_1920)))) begin
        reg_672 <= {{rgb_i_q0[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_2_i_fu_691_p2))) begin
        tmp_13_7_cast_i_reg_1703[15 : 0] <= tmp_13_7_cast_i_fu_700_p1[15 : 0];
        tmp_91_cast_i_reg_1698[15 : 0] <= tmp_91_cast_i_fu_697_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == or_cond13_i_reg_1908) & (ap_const_lv1_0 == or_cond12_i_reg_1912) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        tmp_29_6_i_reg_2050 <= {{rgb_i_q0[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14) & (ap_const_lv1_0 == or_cond15_i_reg_1916) & (ap_const_lv1_0 == or_cond14_i_reg_1920))) begin
        tmp_29_7_i_reg_2075 <= {{rgb_i_q1[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_12)) begin
        tmp_32_i_reg_1752 <= tmp_32_i_fu_882_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == or_cond15_i_reg_1916) & (ap_const_lv1_0 == or_cond14_i_reg_1920) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        tmp_47_i_reg_2055 <= {{rgb_i_q1[ap_const_lv32_7 : ap_const_lv32_5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_11)) begin
        tmp_4_reg_1736 <= tmp_4_fu_819_p1;
        tmp_5_reg_1741 <= tmp_5_i_fu_809_p2[ap_const_lv32_F];
        tmp_7_reg_1747 <= {{mul_i_fu_1643_p2[ap_const_lv32_21 : ap_const_lv32_17]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_345)) begin
        tmp_cast_i_reg_1685 <= tmp_cast_i_fu_676_p1;
    end
end

always @ (ap_done_reg or ap_sig_cseq_ST_st3_fsm_2 or exitcond3_i_fu_703_p2) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond3_i_fu_703_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2 or exitcond3_i_fu_703_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond3_i_fu_703_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_136) begin
    if (ap_sig_bdd_136) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_10 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_425) begin
    if (ap_sig_bdd_425) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_13 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_287) begin
    if (ap_sig_bdd_287) begin
        ap_sig_cseq_ST_pp1_stg10_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg10_fsm_23 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_309) begin
    if (ap_sig_bdd_309) begin
        ap_sig_cseq_ST_pp1_stg11_fsm_24 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg11_fsm_24 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_328) begin
    if (ap_sig_bdd_328) begin
        ap_sig_cseq_ST_pp1_stg1_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg1_fsm_14 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_169) begin
    if (ap_sig_bdd_169) begin
        ap_sig_cseq_ST_pp1_stg2_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg2_fsm_15 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_256) begin
    if (ap_sig_bdd_256) begin
        ap_sig_cseq_ST_pp1_stg3_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg3_fsm_16 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_190) begin
    if (ap_sig_bdd_190) begin
        ap_sig_cseq_ST_pp1_stg4_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg4_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_206) begin
    if (ap_sig_bdd_206) begin
        ap_sig_cseq_ST_pp1_stg5_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg5_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_277) begin
    if (ap_sig_bdd_277) begin
        ap_sig_cseq_ST_pp1_stg6_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg6_fsm_19 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_222) begin
    if (ap_sig_bdd_222) begin
        ap_sig_cseq_ST_pp1_stg7_fsm_20 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg7_fsm_20 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_299) begin
    if (ap_sig_bdd_299) begin
        ap_sig_cseq_ST_pp1_stg8_fsm_21 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg8_fsm_21 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_238) begin
    if (ap_sig_bdd_238) begin
        ap_sig_cseq_ST_pp1_stg9_fsm_22 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg9_fsm_22 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_615) begin
    if (ap_sig_bdd_615) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_404) begin
    if (ap_sig_bdd_404) begin
        ap_sig_cseq_ST_st14_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_417) begin
    if (ap_sig_bdd_417) begin
        ap_sig_cseq_ST_st15_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_44) begin
    if (ap_sig_bdd_44) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_363) begin
    if (ap_sig_bdd_363) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_380) begin
    if (ap_sig_bdd_380) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_727) begin
    if (ap_sig_bdd_727) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (m_axi_frame_in_ARREADY or ap_reg_ioackin_m_axi_frame_in_ARREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axi_frame_in_ARREADY)) begin
        ap_sig_ioackin_m_axi_frame_in_ARREADY = m_axi_frame_in_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_frame_in_ARREADY = ap_const_logic_1;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or featureHist_addr_5_reg_2035 or featureHist_addr_6_reg_2070 or featureHist_addr_7_reg_2080 or featureHist_addr_8_reg_2086 or tmp_1_i_fu_680_p1 or tmp_23_i_fu_1266_p1 or tmp_32_4_i_fu_1526_p1 or tmp_32_5_i_fu_1591_p1 or tmp_32_7_i_fu_1638_p1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19))) begin
        featureHist_address0 = featureHist_addr_8_reg_2086;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        featureHist_address0 = featureHist_addr_7_reg_2080;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        featureHist_address0 = featureHist_addr_6_reg_2070;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        featureHist_address0 = featureHist_addr_5_reg_2035;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        featureHist_address0 = tmp_1_i_fu_680_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18))) begin
        featureHist_address0 = tmp_32_7_i_fu_1638_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14))) begin
        featureHist_address0 = tmp_32_5_i_fu_1591_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24))) begin
        featureHist_address0 = tmp_32_4_i_fu_1526_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16))) begin
        featureHist_address0 = tmp_23_i_fu_1266_p1;
    end else begin
        featureHist_address0 = 'bx;
    end
end

always @ (ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or featureHist_addr_1_reg_1934 or featureHist_addr_2_reg_1960 or featureHist_addr_3_reg_1985 or featureHist_addr_4_reg_2010 or tmp_32_1_i_fu_1331_p1 or tmp_32_2_i_fu_1396_p1 or tmp_32_3_i_fu_1461_p1 or tmp_32_6_i_fu_1615_p1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23))) begin
        featureHist_address1 = featureHist_addr_4_reg_2010;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21))) begin
        featureHist_address1 = featureHist_addr_3_reg_1985;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19))) begin
        featureHist_address1 = featureHist_addr_2_reg_1960;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        featureHist_address1 = featureHist_addr_1_reg_1934;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16))) begin
        featureHist_address1 = tmp_32_6_i_fu_1615_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22))) begin
        featureHist_address1 = tmp_32_3_i_fu_1461_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20))) begin
        featureHist_address1 = tmp_32_2_i_fu_1396_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18))) begin
        featureHist_address1 = tmp_32_1_i_fu_1331_p1;
    end else begin
        featureHist_address1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_pp1_stg0_fsm_13) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14)) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)))) begin
        featureHist_ce0 = ap_const_logic_1;
    end else begin
        featureHist_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16)))) begin
        featureHist_ce1 = ap_const_logic_1;
    end else begin
        featureHist_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or grp_fu_636_p2 or grp_fu_644_p2) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        featureHist_d0 = grp_fu_644_p2;
    end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)))) begin
        featureHist_d0 = grp_fu_636_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        featureHist_d0 = ap_const_lv16_0;
    end else begin
        featureHist_d0 = 'bx;
    end
end

always @ (ap_reg_ppiten_pp1_it0 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or grp_fu_636_p2 or grp_fu_644_p2) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)))) begin
        featureHist_d1 = grp_fu_644_p2;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        featureHist_d1 = grp_fu_636_p2;
    end else begin
        featureHist_d1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or or_cond9_i_reg_1892 or or_cond8_i_reg_1896 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or ap_reg_ppstg_or_cond11_i_reg_1900_pp1_it1 or ap_reg_ppstg_or_cond10_i_reg_1904_pp1_it1 or ap_reg_ppstg_or_cond13_i_reg_1908_pp1_it1 or ap_reg_ppstg_or_cond12_i_reg_1912_pp1_it1 or ap_reg_ppstg_or_cond15_i_reg_1916_pp1_it1 or ap_reg_ppstg_or_cond14_i_reg_1920_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == or_cond9_i_reg_1892) & (ap_const_lv1_0 == or_cond8_i_reg_1896) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond11_i_reg_1900_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond10_i_reg_1904_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond13_i_reg_1908_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond12_i_reg_1912_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond15_i_reg_1916_pp1_it1) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond14_i_reg_1920_pp1_it1)))) begin
        featureHist_we0 = ap_const_logic_1;
    end else begin
        featureHist_we0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp1_it0 or exitcond_flatten_i_reg_1757 or or_cond1_i_reg_1850 or or_cond_i_reg_1854 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or or_cond3_i_reg_1868 or or_cond2_i_reg_1872 or or_cond5_i_reg_1876 or or_cond4_i_reg_1880 or or_cond7_i_reg_1884 or or_cond6_i_reg_1888 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond1_i_reg_1850) & (ap_const_lv1_0 == or_cond_i_reg_1854) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond3_i_reg_1868) & (ap_const_lv1_0 == or_cond2_i_reg_1872) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond5_i_reg_1876) & (ap_const_lv1_0 == or_cond4_i_reg_1880) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_lv1_0 == or_cond7_i_reg_1884) & (ap_const_lv1_0 == or_cond6_i_reg_1888) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)))) begin
        featureHist_we1 = ap_const_logic_1;
    end else begin
        featureHist_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_345) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_345)) begin
        frame_in1_read = ap_const_logic_1;
    end else begin
        frame_in1_read = ap_const_logic_0;
    end
end

always @ (i_i_reg_583 or ap_reg_ppiten_pp1_it1 or exitcond_flatten_i_reg_1757 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or i_mid2_i_reg_1811) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        i_i_phi_fu_587_p4 = i_mid2_i_reg_1811;
    end else begin
        i_i_phi_fu_587_p4 = i_i_reg_583;
    end
end

always @ (indvar2_i_reg_549 or ap_sig_cseq_ST_pp0_stg0_fsm_10 or exitcond5_i_reg_1722 or ap_reg_ppiten_pp0_it1 or indvar_next2_i_reg_1726) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & (ap_const_lv1_0 == exitcond5_i_reg_1722) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        indvar2_i_phi_fu_553_p4 = indvar_next2_i_reg_1726;
    end else begin
        indvar2_i_phi_fu_553_p4 = indvar2_i_reg_549;
    end
end

always @ (indvar_flatten_i_reg_561 or ap_reg_ppiten_pp1_it1 or exitcond_flatten_i_reg_1757 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or indvar_flatten_next_i_reg_1761) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        indvar_flatten_i_phi_fu_565_p4 = indvar_flatten_next_i_reg_1761;
    end else begin
        indvar_flatten_i_phi_fu_565_p4 = indvar_flatten_i_reg_561;
    end
end

always @ (iterator_i_46_reg_594 or ap_reg_ppiten_pp1_it1 or exitcond_flatten_i_reg_1757 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or tmp_34_7_i_reg_1840) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        iterator_i_46_phi_fu_598_p4 = tmp_34_7_i_reg_1840;
    end else begin
        iterator_i_46_phi_fu_598_p4 = iterator_i_46_reg_594;
    end
end

always @ (iterator_i_reg_572 or ap_reg_ppiten_pp1_it1 or exitcond_flatten_i_reg_1757 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or iterator_mid2_i_44_reg_1806) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        iterator_i_phi_fu_576_p4 = iterator_mid2_i_44_reg_1806;
    end else begin
        iterator_i_phi_fu_576_p4 = iterator_i_reg_572;
    end
end

always @ (j_i_reg_605 or ap_reg_ppiten_pp1_it1 or exitcond_flatten_i_reg_1757 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or j_1_7_i_reg_1845) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten_i_reg_1757) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        j_i_phi_fu_609_p4 = j_1_7_i_reg_1845;
    end else begin
        j_i_phi_fu_609_p4 = j_i_reg_605;
    end
end

always @ (ap_reg_ioackin_m_axi_frame_in_ARREADY or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_frame_in_ARREADY))) begin
        m_axi_frame_in_ARVALID = ap_const_logic_1;
    end else begin
        m_axi_frame_in_ARVALID = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_10 or exitcond5_i_reg_1722 or ap_sig_bdd_144 or ap_reg_ppiten_pp0_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_10) & (ap_const_lv1_0 == exitcond5_i_reg_1722) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        m_axi_frame_in_RREADY = ap_const_logic_1;
    end else begin
        m_axi_frame_in_RREADY = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or tmp_12_i_fu_1014_p1 or tmp_20_i_fu_1232_p1 or tmp_23_1_i_fu_1281_p1 or tmp_18_2_i_fu_1296_p1 or tmp_27_2_i_fu_1341_p1 or tmp_23_3_i_fu_1366_p1 or tmp_18_4_i_fu_1406_p1 or tmp_27_4_i_fu_1426_p1 or tmp_23_5_i_fu_1476_p1 or tmp_18_6_i_fu_1491_p1 or tmp_27_6_i_fu_1536_p1 or tmp_23_7_i_fu_1561_p1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        rgb_i_address0 = tmp_23_7_i_fu_1561_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24))) begin
        rgb_i_address0 = tmp_27_6_i_fu_1536_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23))) begin
        rgb_i_address0 = tmp_18_6_i_fu_1491_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22))) begin
        rgb_i_address0 = tmp_23_5_i_fu_1476_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21))) begin
        rgb_i_address0 = tmp_27_4_i_fu_1426_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20))) begin
        rgb_i_address0 = tmp_18_4_i_fu_1406_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19))) begin
        rgb_i_address0 = tmp_23_3_i_fu_1366_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18))) begin
        rgb_i_address0 = tmp_27_2_i_fu_1341_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        rgb_i_address0 = tmp_18_2_i_fu_1296_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16))) begin
        rgb_i_address0 = tmp_23_1_i_fu_1281_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
        rgb_i_address0 = tmp_20_i_fu_1232_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14))) begin
        rgb_i_address0 = tmp_12_i_fu_1014_p1;
    end else begin
        rgb_i_address0 = 'bx;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_pp1_stg0_fsm_13 or tmp_8_i_fu_780_p1 or tmp_15_i_fu_1024_p1 or tmp_18_1_i_fu_1241_p1 or tmp_27_1_i_fu_1286_p1 or tmp_23_2_i_fu_1306_p1 or tmp_18_3_i_fu_1351_p1 or tmp_27_3_i_fu_1371_p1 or tmp_23_4_i_fu_1416_p1 or tmp_18_5_i_fu_1436_p1 or tmp_27_5_i_fu_1481_p1 or tmp_23_6_i_fu_1501_p1 or tmp_18_7_i_fu_1546_p1 or tmp_27_7_i_fu_1566_p1) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
        rgb_i_address1 = tmp_8_i_fu_780_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13))) begin
        rgb_i_address1 = tmp_27_7_i_fu_1566_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24))) begin
        rgb_i_address1 = tmp_18_7_i_fu_1546_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23))) begin
        rgb_i_address1 = tmp_23_6_i_fu_1501_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22))) begin
        rgb_i_address1 = tmp_27_5_i_fu_1481_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21))) begin
        rgb_i_address1 = tmp_18_5_i_fu_1436_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20))) begin
        rgb_i_address1 = tmp_23_4_i_fu_1416_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19))) begin
        rgb_i_address1 = tmp_27_3_i_fu_1371_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18))) begin
        rgb_i_address1 = tmp_18_3_i_fu_1351_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17))) begin
        rgb_i_address1 = tmp_23_2_i_fu_1306_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16))) begin
        rgb_i_address1 = tmp_27_1_i_fu_1286_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
        rgb_i_address1 = tmp_18_1_i_fu_1241_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14))) begin
        rgb_i_address1 = tmp_15_i_fu_1024_p1;
    end else begin
        rgb_i_address1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_pp1_stg0_fsm_13) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14)))) begin
        rgb_i_ce0 = ap_const_logic_1;
    end else begin
        rgb_i_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_144 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp1_stg2_fsm_15 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg4_fsm_17 or ap_sig_cseq_ST_pp1_stg5_fsm_18 or ap_sig_cseq_ST_pp1_stg7_fsm_20 or ap_sig_cseq_ST_pp1_stg9_fsm_22 or ap_sig_cseq_ST_pp1_stg3_fsm_16 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_cseq_ST_pp1_stg10_fsm_23 or ap_sig_cseq_ST_pp1_stg8_fsm_21 or ap_sig_cseq_ST_pp1_stg11_fsm_24 or ap_sig_cseq_ST_pp1_stg1_fsm_14 or ap_sig_cseq_ST_pp1_stg0_fsm_13) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg4_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg5_fsm_18)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg7_fsm_20)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg9_fsm_22)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg3_fsm_16)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg10_fsm_23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg8_fsm_21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg11_fsm_24)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_13)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_14)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        rgb_i_ce1 = ap_const_logic_1;
    end else begin
        rgb_i_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_144 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond5_i_reg_1722_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond5_i_reg_1722_pp0_it1))) begin
        rgb_i_we1 = ap_const_logic_1;
    end else begin
        rgb_i_we1 = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_144 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_pp1_stg6_fsm_19 or ap_sig_bdd_345 or tmp_2_i_fu_691_p2 or exitcond3_i_fu_703_p2 or exitcond5_i_fu_768_p2 or exitcond_flatten_i_fu_889_p2 or ap_sig_ioackin_m_axi_frame_in_ARREADY) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_345) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_lv1_0 == tmp_2_i_fu_691_p2)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == exitcond3_i_fu_703_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_m_axi_frame_in_ARREADY)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_10;
        end
        ap_ST_pp0_stg0_fsm_10 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond5_i_fu_768_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_10;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_144 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond5_i_fu_768_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st14_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_10;
            end
        end
        ap_ST_st14_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_12;
        end
        ap_ST_st15_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg0_fsm_13;
        end
        ap_ST_pp1_stg0_fsm_13 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond_flatten_i_fu_889_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
                ap_NS_fsm = ap_ST_pp1_stg1_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_pp1_stg1_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg2_fsm_15;
        end
        ap_ST_pp1_stg2_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg3_fsm_16;
        end
        ap_ST_pp1_stg3_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg4_fsm_17;
        end
        ap_ST_pp1_stg4_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg5_fsm_18;
        end
        ap_ST_pp1_stg5_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg6_fsm_19;
        end
        ap_ST_pp1_stg6_fsm_19 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg6_fsm_19) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
                ap_NS_fsm = ap_ST_pp1_stg7_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_pp1_stg7_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg8_fsm_21;
        end
        ap_ST_pp1_stg8_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg9_fsm_22;
        end
        ap_ST_pp1_stg9_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg10_fsm_23;
        end
        ap_ST_pp1_stg10_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg11_fsm_24;
        end
        ap_ST_pp1_stg11_fsm_24 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg0_fsm_13;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_136 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end


always @ (m_axi_frame_in_RVALID or exitcond5_i_reg_1722) begin
    ap_sig_bdd_144 = ((m_axi_frame_in_RVALID == ap_const_logic_0) & (ap_const_lv1_0 == exitcond5_i_reg_1722));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_169 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_190 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_206 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_222 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_14]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_238 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_16]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_256 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_277 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_287 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_299 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_15]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_309 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_18]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_328 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end


always @ (ap_start or ap_done_reg or frame_in1_empty_n) begin
    ap_sig_bdd_345 = ((frame_in1_empty_n == ap_const_logic_0) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_363 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_380 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_404 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_417 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_425 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_44 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_615 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_727 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign exitcond1215_i_fu_907_p2 = (j_i_phi_fu_609_p4 == ap_const_lv9_140? 1'b1: 1'b0);

assign exitcond3_i_fu_703_p2 = (k_i_reg_537 == ap_const_lv7_78? 1'b1: 1'b0);

assign exitcond5_i_fu_768_p2 = (indvar2_i_phi_fu_553_p4 == ap_const_lv11_780? 1'b1: 1'b0);

assign exitcond_flatten_i_fu_889_p2 = (indvar_flatten_i_phi_fu_565_p4 == ap_const_lv7_50? 1'b1: 1'b0);

assign grp_fu_616_p4 = {{rgb_i_q0[ap_const_lv32_7 : ap_const_lv32_5]}};

assign grp_fu_636_p2 = (featureHist_q0 + ap_const_lv16_1);

assign grp_fu_644_p2 = (featureHist_q1 + ap_const_lv16_1);

assign i_1211_i_fu_937_p2 = (i_i_phi_fu_587_p4 + ap_const_lv2_1);

assign i_cast_i_fu_951_p1 = i_mid2_i_fu_943_p3;

assign i_mid2_i_fu_943_p3 = ((exitcond1215_i_fu_907_p2[0:0] === 1'b1) ? i_1211_i_fu_937_p2 : i_i_phi_fu_587_p4);

assign indvar_flatten_next_i_fu_895_p2 = (indvar_flatten_i_phi_fu_565_p4 + ap_const_lv7_1);

assign indvar_next2_i_fu_774_p2 = (indvar2_i_phi_fu_553_p4 + ap_const_lv11_1);

assign indvarinc_i_fu_685_p2 = (invdar_i_reg_526 + ap_const_lv9_1);

assign iterator_1_dup_i_fu_901_p2 = (iterator_i_phi_fu_576_p4 + ap_const_lv11_3C0);

assign iterator_mid2_i_44_fu_929_p3 = ((exitcond1215_i_fu_907_p2[0:0] === 1'b1) ? iterator_1_dup_i_fu_901_p2 : iterator_i_phi_fu_576_p4);

assign iterator_mid2_i_fu_913_p3 = ((exitcond1215_i_fu_907_p2[0:0] === 1'b1) ? iterator_1_dup_i_fu_901_p2 : iterator_i_46_phi_fu_598_p4);

assign j_1_1_cast_cast_i_fu_1063_p1 = j_1_1_i_fu_1058_p2;

assign j_1_1_i_fu_1058_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_2);

assign j_1_2_cast_cast_i_fu_1092_p1 = j_1_2_i_fu_1087_p2;

assign j_1_2_i_fu_1087_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_3);

assign j_1_3_cast_cast_i_fu_1121_p1 = j_1_3_i_fu_1116_p2;

assign j_1_3_i_fu_1116_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_4);

assign j_1_4_cast_cast_i_fu_1150_p1 = j_1_4_i_fu_1145_p2;

assign j_1_4_i_fu_1145_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_5);

assign j_1_5_cast_cast_i_fu_1179_p1 = j_1_5_i_fu_1174_p2;

assign j_1_5_i_fu_1174_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_6);

assign j_1_6_cast_cast_i_fu_1208_p1 = j_1_6_i_fu_1203_p2;

assign j_1_6_i_fu_1203_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_7);

assign j_1_7_i_fu_980_p2 = (j_mid2_i_fu_921_p3 + ap_const_lv9_8);

assign j_1_cast_cast_i_fu_1034_p1 = j_1_i_fu_1029_p2;

assign j_1_i_fu_1029_p2 = (j_mid2_i_reg_1794 | ap_const_lv9_1);

assign j_cast_cast_i_fu_986_p1 = j_mid2_i_reg_1794;

assign j_mid2_i_fu_921_p3 = ((exitcond1215_i_fu_907_p2[0:0] === 1'b1) ? ap_const_lv9_0 : j_i_phi_fu_609_p4);

assign k_fu_709_p2 = (k_i_reg_537 + ap_const_lv7_1);

assign m_axi_frame_in_ARADDR = frame_in_addr_reg_1716;

assign m_axi_frame_in_ARBURST = ap_const_lv2_0;

assign m_axi_frame_in_ARCACHE = ap_const_lv4_0;

assign m_axi_frame_in_ARID = ap_const_lv1_0;

assign m_axi_frame_in_ARLEN = ap_const_lv32_780;

assign m_axi_frame_in_ARLOCK = ap_const_lv2_0;

assign m_axi_frame_in_ARPROT = ap_const_lv3_0;

assign m_axi_frame_in_ARQOS = ap_const_lv4_0;

assign m_axi_frame_in_ARREGION = ap_const_lv4_0;

assign m_axi_frame_in_ARSIZE = ap_const_lv3_0;

assign m_axi_frame_in_ARUSER = ap_const_lv1_0;

assign m_axi_frame_in_AWADDR = ap_const_lv32_0;

assign m_axi_frame_in_AWBURST = ap_const_lv2_0;

assign m_axi_frame_in_AWCACHE = ap_const_lv4_0;

assign m_axi_frame_in_AWID = ap_const_lv1_0;

assign m_axi_frame_in_AWLEN = ap_const_lv32_0;

assign m_axi_frame_in_AWLOCK = ap_const_lv2_0;

assign m_axi_frame_in_AWPROT = ap_const_lv3_0;

assign m_axi_frame_in_AWQOS = ap_const_lv4_0;

assign m_axi_frame_in_AWREGION = ap_const_lv4_0;

assign m_axi_frame_in_AWSIZE = ap_const_lv3_0;

assign m_axi_frame_in_AWUSER = ap_const_lv1_0;

assign m_axi_frame_in_AWVALID = ap_const_logic_0;

assign m_axi_frame_in_BREADY = ap_const_logic_0;

assign m_axi_frame_in_WDATA = ap_const_lv8_0;

assign m_axi_frame_in_WID = ap_const_lv1_0;

assign m_axi_frame_in_WLAST = ap_const_logic_0;

assign m_axi_frame_in_WSTRB = ap_const_lv1_0;

assign m_axi_frame_in_WUSER = ap_const_lv1_0;

assign m_axi_frame_in_WVALID = ap_const_logic_0;

assign mul_i_fu_1643_p0 = ap_const_lv34_11112;

assign neg_mul_i_fu_839_p2 = (ap_const_lv33_0 - tmp_4_reg_1736);

assign neg_ti_i_fu_872_p2 = (ap_const_lv9_0 - tmp_8_fu_868_p1);

assign or_cond10_i_fu_1169_p2 = (tmp_14_7_i_reg_1828 | tmp_16_5_i_fu_1164_p2);

assign or_cond11_i_fu_1159_p2 = (tmp_4_i_reg_1816 | tmp_12_5_i_fu_1154_p2);

assign or_cond12_i_fu_1198_p2 = (tmp_14_7_i_reg_1828 | tmp_16_6_i_fu_1193_p2);

assign or_cond13_i_fu_1188_p2 = (tmp_4_i_reg_1816 | tmp_12_6_i_fu_1183_p2);

assign or_cond14_i_fu_1227_p2 = (tmp_14_7_i_reg_1828 | tmp_16_7_i_fu_1222_p2);

assign or_cond15_i_fu_1217_p2 = (tmp_4_i_reg_1816 | tmp_12_7_i_fu_1212_p2);

assign or_cond1_i_fu_994_p2 = (tmp_4_i_reg_1816 | tmp_6_i_fu_989_p2);

assign or_cond2_i_fu_1053_p2 = (tmp_14_7_i_reg_1828 | tmp_16_1_i_fu_1048_p2);

assign or_cond3_i_fu_1043_p2 = (tmp_4_i_reg_1816 | tmp_12_1_i_fu_1038_p2);

assign or_cond4_i_fu_1082_p2 = (tmp_14_7_i_reg_1828 | tmp_16_2_i_fu_1077_p2);

assign or_cond5_i_fu_1072_p2 = (tmp_4_i_reg_1816 | tmp_12_2_i_fu_1067_p2);

assign or_cond6_i_fu_1111_p2 = (tmp_14_7_i_reg_1828 | tmp_16_3_i_fu_1106_p2);

assign or_cond7_i_fu_1101_p2 = (tmp_4_i_reg_1816 | tmp_12_3_i_fu_1096_p2);

assign or_cond8_i_fu_1140_p2 = (tmp_14_7_i_reg_1828 | tmp_16_4_i_fu_1135_p2);

assign or_cond9_i_fu_1130_p2 = (tmp_4_i_reg_1816 | tmp_12_4_i_fu_1125_p2);

assign or_cond_i_fu_1004_p2 = (tmp_14_7_i_reg_1828 | tmp_10_i_fu_999_p2);

assign p_shl1_cast_i_fu_735_p1 = p_shl1_i_fu_727_p3;

assign p_shl1_i_fu_727_p3 = {{k_i_reg_537}, {ap_const_lv7_0}};

assign p_shl2_cast_i_fu_793_p1 = p_shl2_i_fu_785_p3;

assign p_shl2_i_fu_785_p3 = {{k_i_reg_537}, {ap_const_lv8_0}};

assign p_shl3_cast_i_fu_805_p1 = p_shl3_i_fu_797_p3;

assign p_shl3_i_fu_797_p3 = {{k_i_reg_537}, {ap_const_lv4_0}};

assign p_shl_cast_i_fu_723_p1 = p_shl_i_fu_715_p3;

assign p_shl_i_fu_715_p3 = {{k_i_reg_537}, {ap_const_lv11_0}};

assign p_v_i_fu_861_p3 = ((tmp_5_reg_1741[0:0] === 1'b1) ? tmp_13_i_fu_854_p1 : tmp_14_i_fu_858_p1);

assign rgb_i_d1 = frame_in_addr_read_reg_1731;

assign tmp_10_i_fu_999_p2 = (j_cast_cast_i_fu_986_p1 > p_read1? 1'b1: 1'b0);

assign tmp_12_1_i_fu_1038_p2 = (j_1_cast_cast_i_fu_1034_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_2_i_fu_1067_p2 = (j_1_1_cast_cast_i_fu_1063_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_3_i_fu_1096_p2 = (j_1_2_cast_cast_i_fu_1092_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_4_i_fu_1125_p2 = (j_1_3_cast_cast_i_fu_1121_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_5_i_fu_1154_p2 = (j_1_4_cast_cast_i_fu_1150_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_6_i_fu_1183_p2 = (j_1_5_cast_cast_i_fu_1179_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_7_i_fu_1212_p2 = (j_1_6_cast_cast_i_fu_1208_p1 < p_read3? 1'b1: 1'b0);

assign tmp_12_i_fu_1014_p1 = tmp_17_i_fu_1009_p2;

assign tmp_13_7_cast_i_fu_700_p1 = p_read2;

assign tmp_13_i_fu_854_p1 = $signed(tmp_6_fu_844_p4);

assign tmp_14_7_i_fu_969_p2 = ($signed(tmp_13_7_cast_i_reg_1703) < $signed(tmp_cast_i_45_fu_960_p1)? 1'b1: 1'b0);

assign tmp_14_i_fu_858_p1 = $signed(tmp_7_reg_1747);

assign tmp_15_i_fu_1024_p1 = tmp_22_i_fu_1019_p2;

assign tmp_16_1_i_fu_1048_p2 = (j_1_cast_cast_i_fu_1034_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_2_i_fu_1077_p2 = (j_1_1_cast_cast_i_fu_1063_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_3_i_fu_1106_p2 = (j_1_2_cast_cast_i_fu_1092_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_4_i_fu_1135_p2 = (j_1_3_cast_cast_i_fu_1121_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_5_i_fu_1164_p2 = (j_1_4_cast_cast_i_fu_1150_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_6_i_fu_1193_p2 = (j_1_5_cast_cast_i_fu_1179_p1 > p_read1? 1'b1: 1'b0);

assign tmp_16_7_i_fu_1222_p2 = (j_1_6_cast_cast_i_fu_1208_p1 > p_read1? 1'b1: 1'b0);

assign tmp_17_1_i_fu_1236_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_5);

assign tmp_17_2_i_fu_1291_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_8);

assign tmp_17_3_i_fu_1346_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_B);

assign tmp_17_4_i_fu_1401_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_E);

assign tmp_17_5_i_fu_1431_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_11);

assign tmp_17_6_i_fu_1486_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_14);

assign tmp_17_7_i_fu_1541_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_17);

assign tmp_17_i_fu_1009_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_2);

assign tmp_18_1_i_fu_1241_p1 = tmp_17_1_i_fu_1236_p2;

assign tmp_18_2_i_fu_1296_p1 = tmp_17_2_i_fu_1291_p2;

assign tmp_18_3_i_fu_1351_p1 = tmp_17_3_i_fu_1346_p2;

assign tmp_18_4_i_fu_1406_p1 = tmp_17_4_i_fu_1401_p2;

assign tmp_18_5_i_fu_1436_p1 = tmp_17_5_i_fu_1431_p2;

assign tmp_18_6_i_fu_1491_p1 = tmp_17_6_i_fu_1486_p2;

assign tmp_18_7_i_fu_1546_p1 = tmp_17_7_i_fu_1541_p2;

assign tmp_19_i_fu_1246_p4 = {{{reg_652}, {reg_656}}, {ap_const_lv3_0}};

assign tmp_1_fu_749_p1 = $unsigned(tmp_fu_745_p1);

assign tmp_1_i_fu_680_p1 = invdar_i_reg_526;

assign tmp_20_i_fu_1232_p1 = iterator_mid2_i_reg_1766;

assign tmp_22_1_i_fu_1276_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_4);

assign tmp_22_2_i_fu_1301_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_7);

assign tmp_22_3_i_fu_1361_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_A);

assign tmp_22_4_i_fu_1411_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_D);

assign tmp_22_5_i_fu_1471_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_10);

assign tmp_22_6_i_fu_1496_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_13);

assign tmp_22_7_i_fu_1556_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_16);

assign tmp_22_i_49_fu_1260_p2 = (tmp_19_i_fu_1246_p4 | tmp_29_cast_i_fu_1256_p1);

assign tmp_22_i_fu_1019_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_1);

assign tmp_23_1_i_fu_1281_p1 = tmp_22_1_i_fu_1276_p2;

assign tmp_23_2_i_fu_1306_p1 = tmp_22_2_i_fu_1301_p2;

assign tmp_23_3_i_fu_1366_p1 = tmp_22_3_i_fu_1361_p2;

assign tmp_23_4_i_fu_1416_p1 = tmp_22_4_i_fu_1411_p2;

assign tmp_23_5_i_fu_1476_p1 = tmp_22_5_i_fu_1471_p2;

assign tmp_23_6_i_fu_1501_p1 = tmp_22_6_i_fu_1496_p2;

assign tmp_23_7_i_fu_1561_p1 = tmp_22_7_i_fu_1556_p2;

assign tmp_23_i_fu_1266_p1 = tmp_22_i_49_fu_1260_p2;

assign tmp_27_1_i_fu_1286_p1 = tmp_34_i_fu_1271_p2;

assign tmp_27_2_i_fu_1341_p1 = tmp_34_1_i_fu_1336_p2;

assign tmp_27_3_i_fu_1371_p1 = tmp_34_2_i_fu_1356_p2;

assign tmp_27_4_i_fu_1426_p1 = tmp_34_3_i_fu_1421_p2;

assign tmp_27_5_i_fu_1481_p1 = tmp_34_4_i_fu_1466_p2;

assign tmp_27_6_i_fu_1536_p1 = tmp_34_5_i_fu_1531_p2;

assign tmp_27_7_i_fu_1566_p1 = tmp_34_6_i_fu_1551_p2;

assign tmp_29_1_cast_i_fu_1321_p1 = reg_660;

assign tmp_29_2_cast_i_fu_1386_p1 = reg_664;

assign tmp_29_3_cast_i_fu_1451_p1 = reg_656;

assign tmp_29_4_cast_i_fu_1516_p1 = reg_652;

assign tmp_29_5_cast_i_fu_1581_p1 = reg_660;

assign tmp_29_6_cast_i_fu_1606_p1 = tmp_29_6_i_reg_2050;

assign tmp_29_7_cast_i_fu_1629_p1 = tmp_29_7_i_reg_2075;

assign tmp_29_cast_i_fu_1256_p1 = grp_fu_616_p4;

assign tmp_2_fu_753_p2 = ($signed(tmp_cast_i_reg_1685) + $signed(tmp_1_fu_749_p1));

assign tmp_2_i_fu_691_p2 = (invdar_i_reg_526 == ap_const_lv9_1FF? 1'b1: 1'b0);

assign tmp_30_1_i_fu_1311_p4 = {{{reg_656}, {reg_652}}, {ap_const_lv3_0}};

assign tmp_30_2_i_fu_1376_p4 = {{{reg_652}, {reg_656}}, {ap_const_lv3_0}};

assign tmp_30_3_i_fu_1441_p4 = {{{reg_660}, {reg_652}}, {ap_const_lv3_0}};

assign tmp_30_4_i_fu_1506_p4 = {{{reg_664}, {reg_668}}, {ap_const_lv3_0}};

assign tmp_30_5_i_fu_1571_p4 = {{{reg_656}, {reg_672}}, {ap_const_lv3_0}};

assign tmp_30_6_i_fu_1596_p4 = {{{reg_664}, {reg_668}}, {ap_const_lv3_0}};

assign tmp_30_7_i_fu_1620_p4 = {{{tmp_47_i_reg_2055}, {reg_672}}, {ap_const_lv3_0}};

assign tmp_31_1_i_fu_1325_p2 = (tmp_30_1_i_fu_1311_p4 | tmp_29_1_cast_i_fu_1321_p1);

assign tmp_31_2_i_fu_1390_p2 = (tmp_30_2_i_fu_1376_p4 | tmp_29_2_cast_i_fu_1386_p1);

assign tmp_31_3_i_fu_1455_p2 = (tmp_30_3_i_fu_1441_p4 | tmp_29_3_cast_i_fu_1451_p1);

assign tmp_31_4_i_fu_1520_p2 = (tmp_30_4_i_fu_1506_p4 | tmp_29_4_cast_i_fu_1516_p1);

assign tmp_31_5_i_fu_1585_p2 = (tmp_30_5_i_fu_1571_p4 | tmp_29_5_cast_i_fu_1581_p1);

assign tmp_31_6_i_fu_1609_p2 = (tmp_30_6_i_fu_1596_p4 | tmp_29_6_cast_i_fu_1606_p1);

assign tmp_31_7_i_fu_1632_p2 = (tmp_30_7_i_fu_1620_p4 | tmp_29_7_cast_i_fu_1629_p1);

assign tmp_32_1_i_fu_1331_p1 = tmp_31_1_i_fu_1325_p2;

assign tmp_32_2_i_fu_1396_p1 = tmp_31_2_i_fu_1390_p2;

assign tmp_32_3_i_fu_1461_p1 = tmp_31_3_i_fu_1455_p2;

assign tmp_32_4_i_fu_1526_p1 = tmp_31_4_i_fu_1520_p2;

assign tmp_32_5_i_fu_1591_p1 = tmp_31_5_i_fu_1585_p2;

assign tmp_32_6_i_fu_1615_p1 = tmp_31_6_i_fu_1609_p2;

assign tmp_32_7_i_fu_1638_p1 = tmp_31_7_i_fu_1632_p2;

assign tmp_32_i_fu_882_p3 = ((tmp_5_reg_1741[0:0] === 1'b1) ? neg_ti_i_fu_872_p2 : tmp_9_fu_878_p1);

assign tmp_34_1_i_fu_1336_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_6);

assign tmp_34_2_i_fu_1356_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_9);

assign tmp_34_3_i_fu_1421_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_C);

assign tmp_34_4_i_fu_1466_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_F);

assign tmp_34_5_i_fu_1531_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_12);

assign tmp_34_6_i_fu_1551_p2 = (iterator_mid2_i_reg_1766 + ap_const_lv11_15);

assign tmp_34_7_i_fu_974_p2 = (iterator_mid2_i_fu_913_p3 + ap_const_lv11_18);

assign tmp_34_i_fu_1271_p2 = (iterator_mid2_i_reg_1766 | ap_const_lv11_3);

assign tmp_3_fu_758_p1 = $signed(tmp_2_fu_753_p2);

assign tmp_3_i_fu_739_p2 = (p_shl_cast_i_fu_723_p1 - p_shl1_cast_i_fu_735_p1);

assign tmp_4_fu_819_p1 = mul_i_fu_1643_p2[32:0];

assign tmp_4_i_fu_964_p2 = ($signed(tmp_91_cast_i_reg_1698) > $signed(tmp_cast_i_45_fu_960_p1)? 1'b1: 1'b0);

assign tmp_5_i_fu_809_p2 = (p_shl2_cast_i_fu_793_p1 - p_shl3_cast_i_fu_805_p1);

assign tmp_6_fu_844_p4 = {{neg_mul_i_fu_839_p2[ap_const_lv32_20 : ap_const_lv32_17]}};

assign tmp_6_i_fu_989_p2 = (j_cast_cast_i_fu_986_p1 < p_read3? 1'b1: 1'b0);

assign tmp_8_fu_868_p1 = p_v_i_fu_861_p3[8:0];

assign tmp_8_i_fu_780_p1 = ap_reg_ppstg_indvar2_i_reg_549_pp0_it1;

assign tmp_91_cast_i_fu_697_p1 = p_read;

assign tmp_9_fu_878_p1 = p_v_i_fu_861_p3[8:0];

assign tmp_cast_i_45_fu_960_p1 = $signed(tmp_i_fu_955_p2);

assign tmp_cast_i_fu_676_p1 = $signed(frame_in1_dout);

assign tmp_fu_745_p1 = $signed(tmp_3_i_fu_739_p2);

assign tmp_i_fu_955_p2 = (tmp_32_i_reg_1752 + i_cast_i_fu_951_p1);
always @ (posedge ap_clk) begin
    tmp_91_cast_i_reg_1698[16] <= 1'b0;
    tmp_13_7_cast_i_reg_1703[16] <= 1'b0;
end



endmodule //feature_Loop_memset_featureHist_proc1

