// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CRTL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of init
//        bit 0  - init[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBGSUB_CRTL_BUS_ADDR_AP_CTRL   0x00
#define XBGSUB_CRTL_BUS_ADDR_GIE       0x04
#define XBGSUB_CRTL_BUS_ADDR_IER       0x08
#define XBGSUB_CRTL_BUS_ADDR_ISR       0x0c
#define XBGSUB_CRTL_BUS_ADDR_INIT_DATA 0x10
#define XBGSUB_CRTL_BUS_BITS_INIT_DATA 1

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of frame_in
//        bit 31~0 - frame_in[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of frame_out
//        bit 31~0 - frame_out[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of bgmodel
//        bit 31~0 - bgmodel[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBGSUB_AXILITES_ADDR_FRAME_IN_DATA  0x10
#define XBGSUB_AXILITES_BITS_FRAME_IN_DATA  32
#define XBGSUB_AXILITES_ADDR_FRAME_OUT_DATA 0x18
#define XBGSUB_AXILITES_BITS_FRAME_OUT_DATA 32
#define XBGSUB_AXILITES_ADDR_BGMODEL_DATA   0x20
#define XBGSUB_AXILITES_BITS_BGMODEL_DATA   32

