// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XBGSUB_H
#define XBGSUB_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbgsub_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
    u32 Axilites_BaseAddress;
} XBgsub_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XBgsub;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBgsub_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBgsub_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBgsub_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBgsub_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBgsub_Initialize(XBgsub *InstancePtr, u16 DeviceId);
XBgsub_Config* XBgsub_LookupConfig(u16 DeviceId);
int XBgsub_CfgInitialize(XBgsub *InstancePtr, XBgsub_Config *ConfigPtr);
#else
int XBgsub_Initialize(XBgsub *InstancePtr, const char* InstanceName);
int XBgsub_Release(XBgsub *InstancePtr);
#endif

void XBgsub_Start(XBgsub *InstancePtr);
u32 XBgsub_IsDone(XBgsub *InstancePtr);
u32 XBgsub_IsIdle(XBgsub *InstancePtr);
u32 XBgsub_IsReady(XBgsub *InstancePtr);
void XBgsub_EnableAutoRestart(XBgsub *InstancePtr);
void XBgsub_DisableAutoRestart(XBgsub *InstancePtr);

void XBgsub_Set_init(XBgsub *InstancePtr, u32 Data);
u32 XBgsub_Get_init(XBgsub *InstancePtr);
void XBgsub_Set_frame_in(XBgsub *InstancePtr, u32 Data);
u32 XBgsub_Get_frame_in(XBgsub *InstancePtr);
void XBgsub_Set_frame_out(XBgsub *InstancePtr, u32 Data);
u32 XBgsub_Get_frame_out(XBgsub *InstancePtr);
void XBgsub_Set_bgmodel(XBgsub *InstancePtr, u32 Data);
u32 XBgsub_Get_bgmodel(XBgsub *InstancePtr);

void XBgsub_InterruptGlobalEnable(XBgsub *InstancePtr);
void XBgsub_InterruptGlobalDisable(XBgsub *InstancePtr);
void XBgsub_InterruptEnable(XBgsub *InstancePtr, u32 Mask);
void XBgsub_InterruptDisable(XBgsub *InstancePtr, u32 Mask);
void XBgsub_InterruptClear(XBgsub *InstancePtr, u32 Mask);
u32 XBgsub_InterruptGetEnabled(XBgsub *InstancePtr);
u32 XBgsub_InterruptGetStatus(XBgsub *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
