// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbgsub.h"

extern XBgsub_Config XBgsub_ConfigTable[];

XBgsub_Config *XBgsub_LookupConfig(u16 DeviceId) {
	XBgsub_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBGSUB_NUM_INSTANCES; Index++) {
		if (XBgsub_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBgsub_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBgsub_Initialize(XBgsub *InstancePtr, u16 DeviceId) {
	XBgsub_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBgsub_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBgsub_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

